[package]
name = "agena-keyring-store"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[dependencies]
keyring = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
parking_lot = { workspace = true }

[lints]
workspace = true
