[package]
name = "agena-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[dependencies]
agena = { workspace = true }
agena-api = { workspace = true }
agena-api-server = { workspace = true }
agena-skills = { workspace = true }
agena-tui-components = { workspace = true }
arboard = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true, features = ["event-stream"] }
fluent-templates = { workspace = true }
futures-util = { workspace = true }
ignore = { workspace = true }
image = { workspace = true }
imagesize = { workspace = true }
indexmap = { workspace = true }
mime_guess = { workspace = true }
ratatui = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls"] }
regex = { workspace = true }
sea-orm = { workspace = true, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shlex = { workspace = true }
sys-locale = { workspace = true }
tempfile = { workspace = true }
textwrap = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
tui-markdown = "0.3.7"
unic-langid = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
