[package]
name = "agena-client"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
agena-api = { path = "../agena-api" }
agena = { path = "../agena" }
async-trait = { workspace = true }
futures-util = "0.3.31"
reqwest = { workspace = true, features = ["json", "rustls", "stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
smol_str = { version = "0.3.2", features = ["serde"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "net", "time", "io-util"] }
tokio-tungstenite = { version = "0.28.0", default-features = false, features = ["connect", "rustls-tls-webpki-roots"] }
tracing = { workspace = true }
url = "2.5.8"
uuid = { workspace = true }

[dev-dependencies]
agena = { path = "../agena" }
agena-api-server = { path = "../agena-api-server" }
axum = { workspace = true }
sea-orm = { version = "1.1.19", default-features = false, features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros", "with-json"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }

[lints]
workspace = true
