[package]
name = "agena-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[dependencies]
agena-domain = { workspace = true }
agena-api = { workspace = true }
agena-failure = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls", "stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "net", "time", "io-util"] }
tokio-tungstenite = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
