[package]
name = "agena-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[dependencies]
agena-domain = { workspace = true }
agena-failure = { workspace = true }
agena-notification = { workspace = true }
agena-plugin-sdk = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smol_str = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
