import { computed } from 'vue'

import type { RouteLocationNormalizedLoaded, Router } from 'vue-router'

import { runtimeTabs, type RuntimeRouteSection } from './runtimePageStateModel'
import { useRuntimeDerivedState } from './useRuntimeDerivedState'
import { useRuntimePageAssembly } from './useRuntimePageAssembly'
import { useRuntimePageStore } from './useRuntimePageStore'

export function useRuntimePageState(input: {
  route: RouteLocationNormalizedLoaded
  router: Router
  section?: RuntimeRouteSection
}) {
  const {
    activePluginsTab,
    activeSettingsTab,
    activeTab,
    actionError,
    actionMessage,
    authProviders,
    browserAuthCodeDrafts,
    browserAuthInstanceDrafts,
    browserAuthStartState,
    catalogEntries,
    desktopConfig,
    desktopForm,
    desktopInstallerAssetName,
    desktopInstallerUpdateUrl,
    desktopNotice,
    desktopRuntimeState,
    desktopSaving,
    desktopServiceUpdateUrl,
    desktopStatus,
    desktopUpdate,
    desktopUpdateRunning,
    deviceAuthEnterpriseDrafts,
    deviceAuthStartState,
    drafts,
    editingPermissionRuleId,
    globalEvents,
    loading,
    lspQuery,
    marketplaceAllowUnverified,
    marketplaceCascadeUninstall,
    marketplaceInstallSpec,
    marketplaceInstalled,
    marketplaceLoading,
    marketplaceOutdated,
    marketplacePlugins,
    marketplaceQuery,
    marketplaceRefreshIndex,
    marketplaceRegistryId,
    marketplaceRegistryUrl,
    marketplaceRequireSignature,
    mcpQuery,
    permissionDraft,
    permissionModeFilter,
    permissionRules,
    permissionScopeFilter,
    permissionSearch,
    permissionStatusFilter,
    permissionSubjectFilter,
    pluginLoading,
    pluginLogPollTimer,
    pluginLogs,
    plugins,
    settingsPlugins,
    providerModels,
    providers,
    runtime,
    runtimeSkillQuery,
    selectedPlugin,
    selectedPluginId,
    selectedSessionId,
    selectedWorkspaceId,
    sessionExecution,
    sessions,
    sessionTimeline,
    workflowLoading,
    workspaces,
  } = useRuntimePageStore()

  const derived = useRuntimeDerivedState({
    desktopConfig,
    desktopRuntimeState,
    desktopStatus,
    desktopUpdate,
    lspQuery,
    marketplaceInstalled,
    marketplacePlugins,
    marketplaceQuery,
    mcpQuery,
    permissionModeFilter,
    permissionRules,
    permissionScopeFilter,
    permissionStatusFilter,
    permissionSubjectFilter,
    routePath: computed(() => input.route.path),
    runtime,
    runtimeSkillQuery,
    section: input.section,
    selectedPlugin,
    globalEvents,
    sessionExecution,
    sessionTimeline,
    tabs: runtimeTabs,
  })
  const {
    desktopBackendErrorFacts,
    desktopBackendUrl,
    desktopConfigFacts,
    desktopEnabled,
    desktopRuntimeFacts,
    desktopStatusFacts,
    desktopUpdateFacts,
    desktopUpdateProgressPercent,
    discoveredSkills,
    executionFacts,
    filteredDiscoveredSkills,
    filteredLspServers,
    filteredMarketplacePlugins,
    filteredMcpServers,
    filteredPermissionRules,
    filteredSkillCommands,
    globalEventSummaries,
    installedMarketplacePluginIds,
    operatorCards,
    pageDescription,
    pageTitle,
    routeSection,
    runtimeSnapshotFacts,
    selectedPluginManifest,
    sessionCacheFacts,
    skillCommands,
    timelineSummaries,
    visibleTabs,
  } = derived
  const {
    desktopActions,
    loadPageState,
    marketplaceActions,
    navigation,
    permissionActions,
    pluginDetails,
    providerActions,
    sessionWorkflowActions,
  } = useRuntimePageAssembly({
    activePluginsTab,
    activeSettingsTab,
    activeTab,
    actionError,
    actionMessage,
    authProviders,
    browserAuthCodeDrafts,
    browserAuthInstanceDrafts,
    browserAuthStartState,
    catalogEntries,
    desktopBackendUrl,
    desktopConfig,
    desktopEnabled,
    desktopForm,
    desktopInstallerAssetName,
    desktopInstallerUpdateUrl,
    desktopNotice,
    desktopRuntimeState,
    desktopSaving,
    desktopServiceUpdateUrl,
    desktopStatus,
    desktopUpdate,
    desktopUpdateRunning,
    deviceAuthEnterpriseDrafts,
    deviceAuthStartState,
    drafts,
    editingPermissionRuleId,
    globalEvents,
    loading,
    lspQuery,
    marketplaceAllowUnverified,
    marketplaceCascadeUninstall,
    marketplaceInstallSpec,
    marketplaceInstalled,
    marketplaceLoading,
    marketplaceOutdated,
    marketplacePlugins,
    marketplaceQuery,
    marketplaceRefreshIndex,
    marketplaceRegistryId,
    marketplaceRegistryUrl,
    marketplaceRequireSignature,
    mcpQuery,
    permissionDraft,
    permissionModeFilter,
    permissionRules,
    permissionScopeFilter,
    permissionSearch,
    permissionStatusFilter,
    permissionSubjectFilter,
    pluginLoading,
    pluginLogPollTimer,
    pluginLogs,
    plugins,
    settingsPlugins,
    providerModels,
    providers,
    routePath: computed(() => input.route.path),
    routeQuery: input.route.query,
    router: input.router,
    routeSection,
    runtime,
    runtimeSkillQuery,
    selectedPlugin,
    selectedPluginId,
    selectedPluginManifest,
    selectedSessionId,
    selectedWorkspaceId,
    sessionExecution,
    sessions,
    sessionTimeline,
    workflowLoading,
    workspaces,
  })

  const {
    selectSession,
    selectWorkspace,
    triggerReload,
  } = sessionWorkflowActions

  const {
    loadDesktopPanel,
    openDesktopBackendUrlAction,
    openDesktopConfigAction,
    refreshDesktopUpdateProgressAction,
    restartDesktopBackendAction,
    runDesktopInstallerUpdateAction,
    runDesktopServiceUpdateAction,
    saveDesktopConfigAction,
  } = desktopActions

  const {
    installMarketplacePluginAction,
    searchMarketplaceAction,
    syncMarketplaceRegistryAction,
    uninstallMarketplacePluginAction,
    upgradeMarketplacePluginAction,
  } = marketplaceActions

  const {
    canTogglePluginConfig,
    loadPluginDetails,
    setSelectedPluginDisabled,
  } = pluginDetails

  const {
    approvePermission,
    editPermissionRequest,
    deletePermissionRuleAction,
    editPermissionRule,
    permissionRuleFacts,
    permissionRuleLabel,
    permissionRulePreview,
    resetPermissionDraft,
    revokePermissionRuleAction,
    savePermissionRule,
  } = permissionActions

  const {
    clearCredential,
    finishBrowserAuth,
    handleBrowserAuthCallback,
    pollDeviceAuth,
    refreshCredential,
    saveApiKey,
    startBrowserAuth,
    startDeviceAuth,
  } = providerActions

  const {
    openPluginLogsWorkspacePath,
    openPluginManifestInWorkspace,
    openRuntimeConfigRoot,
    openRuntimeEntryInChat,
    openRuntimeEntrySource,
    openSelectedSessionInChat,
    openWorkspacePath,
    openWorkspaceShortcut,
  } = navigation

  return {
    activePluginsTab,
    activeSettingsTab,
    activeTab,
    actionError,
    actionMessage,
    approvePermission,
    editPermissionRequest,
    authProviders,
    browserAuthCodeDrafts,
    browserAuthInstanceDrafts,
    browserAuthStartState,
    catalogEntries,
    clearCredential,
    desktopBackendErrorFacts,
    desktopBackendUrl,
    desktopConfig,
    desktopConfigFacts,
    desktopEnabled,
    desktopForm,
    desktopInstallerAssetName,
    desktopInstallerUpdateUrl,
    desktopNotice,
    desktopRuntimeFacts,
    desktopSaving,
    desktopServiceUpdateUrl,
    desktopStatusFacts,
    desktopUpdateFacts,
    desktopUpdateProgressPercent,
    desktopUpdateRunning,
    deviceAuthEnterpriseDrafts,
    deviceAuthStartState,
    deletePermissionRuleAction,
    discoveredSkills,
    filteredDiscoveredSkills,
    filteredLspServers,
    filteredMcpServers,
    filteredSkillCommands,
    drafts,
    editPermissionRule,
    editingPermissionRuleId,
    executionFacts,
    installedMarketplacePluginIds,
    installMarketplacePluginAction,
    marketplaceAllowUnverified,
    marketplaceCascadeUninstall,
    marketplaceInstallSpec,
    marketplaceInstalled,
    marketplaceLoading,
    marketplaceOutdated,
    marketplacePlugins,
    marketplaceRefreshIndex,
    marketplaceRegistryId,
    marketplaceRegistryUrl,
    marketplaceRequireSignature,
    openRuntimeEntrySource,
    openWorkspacePath,
    filteredMarketplacePlugins,
    filteredPermissionRules,
    globalEventSummaries,
    load: loadPageState,
    loadDesktopPanel,
    canTogglePluginConfig,
    loadPluginDetails,
    setSelectedPluginDisabled,
    loading,
    marketplaceQuery,
    mcpQuery,
    lspQuery,
    openDesktopBackendUrlAction,
    runtimeSkillQuery,
    openDesktopConfigAction,
    openRuntimeConfigRoot,
    openRuntimeEntryInChat,
    openPluginLogsWorkspacePath,
    openPluginManifestInWorkspace,
    openSelectedSessionInChat,
    openWorkspaceShortcut,
    finishBrowserAuth,
    handleBrowserAuthCallback,
    operatorCards,
    pageDescription,
    pageTitle,
    permissionDraft,
    permissionModeFilter,
    permissionRuleFacts,
    permissionRuleLabel,
    permissionRulePreview,
    permissionScopeFilter,
    permissionSearch,
    permissionStatusFilter,
    permissionSubjectFilter,
    pluginLoading,
    pluginLogs,
    plugins,
    settingsPlugins,
    providers,
    providerModels,
    refreshCredential,
    pollDeviceAuth,
    searchMarketplaceAction,
    refreshDesktopUpdateProgressAction,
    resetPermissionDraft,
    restartDesktopBackendAction,
    runDesktopInstallerUpdateAction,
    runDesktopServiceUpdateAction,
    revokePermissionRuleAction,
    syncMarketplaceRegistryAction,
    routeSection,
    runtime,
    runtimeSnapshotFacts,
    saveApiKey,
    startBrowserAuth,
    startDeviceAuth,
    saveDesktopConfigAction,
    savePermissionRule,
    selectSession,
    selectWorkspace,
    selectedPlugin,
    selectedPluginId,
    selectedSessionId,
    selectedWorkspaceId,
    sessionCacheFacts,
    sessionExecution,
    sessions,
    sessionTimeline,
    skillCommands,
    timelineSummaries,
    triggerReload,
    uninstallMarketplacePluginAction,
    upgradeMarketplacePluginAction,
    visibleTabs,
    workflowLoading,
    workspaces,
  }
}
