[package]
name = "agena-event-store-sea"
version = "0.1.0"
edition = "2024"

[dependencies]
agena-event = { path = "../agena-event" }
async-trait = "0.1.89"
chrono = { version = "0.4.42", features = ["serde"] }
sea-orm = { version = "1.1.19", default-features = false, features = ["macros", "with-json"] }
sea-orm-migration = { version = "1.1.19", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
uuid = { version = "1.18.1", features = ["v4", "serde"] }

[dev-dependencies]
agena-event = { path = "../agena-event" }
sea-orm = { version = "1.1.19", default-features = false, features = ["macros", "with-json", "sqlx-sqlite", "runtime-tokio-rustls"] }
sea-orm-migration = { version = "1.1.19", default-features = false, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.228", features = ["derive"] }
