import { computed } from 'vue'

import type { RouteLocationNormalizedLoaded, Router } from 'vue-router'

import { usePluginToolRegistryRuntimeSync } from '../lib/usePluginToolRegistryRuntimeSync'
import { userErrorMessage } from '@/lib/api'
import { runtimeTabs, type RuntimeRouteSection } from './runtimePageStateModel'
import { useRuntimeDerivedState } from './useRuntimeDerivedState'
import { useRuntimePageAssembly } from './useRuntimePageAssembly'
import { useRuntimePageStore } from './useRuntimePageStore'

export function useRuntimePageState(input: {
  route: RouteLocationNormalizedLoaded
  router: Router
  section?: RuntimeRouteSection
}) {
  const {
    activePluginsTab,
    activeSettingsTab,
    activeTab,
    actionError,
    actionMessage,
    authProviders,
    browserAuthCodeDrafts,
    browserAuthInstanceDrafts,
    browserAuthStartState,
    catalogEntries,
    deviceAuthEnterpriseDrafts,
    deviceAuthStartState,
    drafts,
    editingPermissionRuleId,
    globalEvents,
    interactiveRequestInFlight,
    loading,
    lspQuery,
    marketplaceAllowUnverified,
    marketplaceCascadeUninstall,
    marketplaceInstallSpec,
    marketplaceInstalled,
    marketplaceLoading,
    marketplaceOutdated,
    marketplacePlugins,
    marketplaceQuery,
    marketplaceRefreshIndex,
    marketplaceRegistryId,
    marketplaceRegistryUrl,
    marketplaceRequireSignature,
    mcpQuery,
    permissionConfig,
    permissionDraft,
    permissionModeFilter,
    permissionRules,
    permissionSearch,
    permissionScopeFilter,
    permissionStatusFilter,
    permissionSubjectFilter,
    pluginLoading,
    pluginLogPollTimer,
    pluginLogs,
    pluginUiPresentation,
    plugins,
    settingsPlugins,
    providerModels,
    providers,
    runtime,
    runtimeSkillQuery,
    selectedPlugin,
    selectedPluginId,
    selectedSessionId,
    selectedWorkspaceId,
    sessionExecution,
    sessions,
    sessionTimeline,
    workflowLoading,
    workspaces,
  } = useRuntimePageStore()

  usePluginToolRegistryRuntimeSync(
    {
      runtime,
    },
    undefined,
    {
      onError: (error) => {
        actionError.value = userErrorMessage(error, 'Runtime updates were interrupted. Reconnecting…')
      },
    },
  )

  const derived = useRuntimeDerivedState({
    lspQuery,
    marketplaceInstalled,
    marketplacePlugins,
    marketplaceQuery,
    mcpQuery,
    permissionModeFilter,
    permissionRules,
    permissionSearch,
    permissionScopeFilter,
    permissionStatusFilter,
    permissionSubjectFilter,
    routePath: computed(() => input.route.path),
    runtime,
    runtimeSkillQuery,
    section: input.section,
    selectedPlugin,
    globalEvents,
    sessionExecution,
    sessionTimeline,
    tabs: runtimeTabs,
  })
  const {
    discoveredSkills,
    executionFacts,
    filteredDiscoveredSkills,
    filteredLspServers,
    filteredMarketplacePlugins,
    filteredMcpServers,
    filteredPermissionRules,
    filteredSkillCommands,
    globalEventSummaries,
    installedMarketplacePluginIds,
    operatorCards,
    pageDescription,
    pageTitle,
    routeSection,
    runtimeSnapshotFacts,
    selectedPluginManifest,
    sessionCacheFacts,
    skillCommands,
    timelineSummaries,
    visibleTabs,
  } = derived
  const {
    loadPageState,
    marketplaceActions,
    navigation,
    permissionActions,
    pluginDetails,
    providerActions,
    sessionWorkflowActions,
  } = useRuntimePageAssembly({
    activePluginsTab,
    activeSettingsTab,
    activeTab,
    actionError,
    actionMessage,
    authProviders,
    browserAuthCodeDrafts,
    browserAuthInstanceDrafts,
    browserAuthStartState,
    catalogEntries,
    deviceAuthEnterpriseDrafts,
    deviceAuthStartState,
    drafts,
    editingPermissionRuleId,
    globalEvents,
    interactiveRequestInFlight,
    loading,
    lspQuery,
    marketplaceAllowUnverified,
    marketplaceCascadeUninstall,
    marketplaceInstallSpec,
    marketplaceInstalled,
    marketplaceLoading,
    marketplaceOutdated,
    marketplacePlugins,
    marketplaceQuery,
    marketplaceRefreshIndex,
    marketplaceRegistryId,
    marketplaceRegistryUrl,
    marketplaceRequireSignature,
    mcpQuery,
    permissionConfig,
    permissionDraft,
    permissionModeFilter,
    permissionRules,
    permissionScopeFilter,
    permissionSearch,
    permissionStatusFilter,
    permissionSubjectFilter,
    pluginLoading,
    pluginLogPollTimer,
    pluginLogs,
    pluginUiPresentation,
    plugins,
    settingsPlugins,
    providerModels,
    providers,
    routePath: computed(() => input.route.path),
    routeQuery: computed(() => input.route.query),
    router: input.router,
    routeSection,
    runtime,
    runtimeSkillQuery,
    selectedPlugin,
    selectedPluginId,
    selectedPluginManifest,
    selectedSessionId,
    selectedWorkspaceId,
    sessionExecution,
    sessions,
    sessionTimeline,
    workflowLoading,
    workspaces,
  })

  const { selectSession, selectWorkspace, triggerReload } = sessionWorkflowActions

  const {
    installMarketplacePluginAction,
    searchMarketplaceAction,
    syncMarketplaceRegistryAction,
    uninstallMarketplacePluginAction,
    upgradeMarketplacePluginAction,
  } = marketplaceActions

  const { canTogglePluginConfig, loadPluginDetails, setSelectedPluginDisabled } = pluginDetails

  const {
    approvePermission,
    editPermissionRequest,
    deletePermissionRuleAction,
    editPermissionRule,
    isInteractiveRequestBusy,
    permissionRuleFacts,
    permissionRuleLabel,
    permissionRulePreview,
    resetPermissionDraft,
    revokePermissionRuleAction,
    savePermissionRule,
  } = permissionActions

  const {
    clearCredential,
    finishBrowserAuth,
    handleBrowserAuthCallback,
    pollDeviceAuth,
    refreshCredential,
    saveApiKey,
    startBrowserAuth,
    startDeviceAuth,
  } = providerActions

  const {
    openPluginLogsWorkspacePath,
    openPluginManifestInWorkspace,
    openRuntimeConfigRoot,
    openRuntimeEntryInChat,
    openRuntimeEntrySource,
    openSelectedSessionInChat,
    openWorkspacePath,
    openWorkspaceShortcut,
  } = navigation

  return {
    activePluginsTab,
    activeSettingsTab,
    activeTab,
    actionError,
    actionMessage,
    approvePermission,
    editPermissionRequest,
    isInteractiveRequestBusy,
    authProviders,
    browserAuthCodeDrafts,
    browserAuthInstanceDrafts,
    browserAuthStartState,
    catalogEntries,
    clearCredential,
    deviceAuthEnterpriseDrafts,
    deviceAuthStartState,
    deletePermissionRuleAction,
    discoveredSkills,
    filteredDiscoveredSkills,
    filteredLspServers,
    filteredMcpServers,
    filteredSkillCommands,
    drafts,
    editPermissionRule,
    editingPermissionRuleId,
    executionFacts,
    installedMarketplacePluginIds,
    installMarketplacePluginAction,
    marketplaceAllowUnverified,
    marketplaceCascadeUninstall,
    marketplaceInstallSpec,
    marketplaceInstalled,
    marketplaceLoading,
    marketplaceOutdated,
    marketplacePlugins,
    marketplaceRefreshIndex,
    marketplaceRegistryId,
    marketplaceRegistryUrl,
    marketplaceRequireSignature,
    openRuntimeEntrySource,
    openWorkspacePath,
    filteredMarketplacePlugins,
    filteredPermissionRules,
    globalEventSummaries,
    load: loadPageState,
    canTogglePluginConfig,
    loadPluginDetails,
    setSelectedPluginDisabled,
    loading,
    marketplaceQuery,
    mcpQuery,
    lspQuery,
    runtimeSkillQuery,
    openRuntimeConfigRoot,
    openRuntimeEntryInChat,
    openPluginLogsWorkspacePath,
    openPluginManifestInWorkspace,
    openSelectedSessionInChat,
    openWorkspaceShortcut,
    finishBrowserAuth,
    handleBrowserAuthCallback,
    operatorCards,
    pageDescription,
    pageTitle,
    permissionConfig,
    permissionDraft,
    permissionModeFilter,
    permissionRuleFacts,
    permissionRuleLabel,
    permissionRulePreview,
    permissionScopeFilter,
    permissionSearch,
    permissionStatusFilter,
    permissionSubjectFilter,
    pluginLoading,
    pluginLogs,
    pluginUiPresentation,
    plugins,
    settingsPlugins,
    providers,
    providerModels,
    refreshCredential,
    pollDeviceAuth,
    searchMarketplaceAction,
    resetPermissionDraft,
    revokePermissionRuleAction,
    syncMarketplaceRegistryAction,
    routeSection,
    runtime,
    runtimeSnapshotFacts,
    saveApiKey,
    startBrowserAuth,
    startDeviceAuth,
    savePermissionRule,
    selectSession,
    selectWorkspace,
    selectedPlugin,
    selectedPluginId,
    selectedSessionId,
    selectedWorkspaceId,
    sessionCacheFacts,
    sessionExecution,
    sessions,
    sessionTimeline,
    skillCommands,
    timelineSummaries,
    triggerReload,
    uninstallMarketplacePluginAction,
    upgradeMarketplacePluginAction,
    visibleTabs,
    workflowLoading,
    workspaces,
  }
}
