#!/usr/bin/env bash
set -euo pipefail

TARGET="${1:?Haiku target triple is required}"
shift
[[ "${1:-}" == -- ]] && shift
[[ $# -gt 0 ]] || { echo "ERROR: command is required" >&2; exit 2; }

case "$(uname -s)-$(uname -m)" in
  Linux-x86_64) ;;
  *) echo "ERROR: Haiku cross-tools builder requires Linux x86_64" >&2; exit 2 ;;
esac

case "$TARGET" in
  i686-unknown-haiku)
    HAIKU_ARCH=x86
    GNU_TARGET=i586-pc-haiku
    CFLAGS_EXTRA=-m32
    ;;
  x86_64-unknown-haiku)
    HAIKU_ARCH=x86_64
    GNU_TARGET=x86_64-unknown-haiku
    CFLAGS_EXTRA=-m64
    ;;
  *) echo "ERROR: unsupported Haiku target: $TARGET" >&2; exit 2 ;;
esac

# Pin both official Haiku GitHub mirrors so cross-tools/sysroot generation is
# reproducible rather than following moving master branches.
HAIKU_COMMIT=dfaff659fa944da59db4014f50cde2daea9415bd
BUILDTOOLS_COMMIT=8375c2dbeaf109c520798cb234d57f0895463201
PATCH_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/third_party/haiku-bootstrap-smbios.patch"
ROOT="${RUNNER_TEMP:-/tmp}/agena-haiku/$HAIKU_ARCH"
HAIKU="$ROOT/haiku"
BUILDTOOLS="$ROOT/buildtools"
OUTPUT="$ROOT/generated"
PACKAGE_ROOT="$ROOT/system"
SYSROOT="$OUTPUT/cross-tools-$HAIKU_ARCH/sysroot"
TOOLBIN="$OUTPUT/cross-tools-$HAIKU_ARCH/bin"
mkdir -p "$ROOT"

valid_toolchain() {
  [[ -x "$TOOLBIN/$GNU_TARGET-gcc" ]] \
    && [[ -f "$PACKAGE_ROOT/develop/headers/posix/stdio.h" || -f "$PACKAGE_ROOT/develop/headers/stdio.h" ]] \
    && find "$PACKAGE_ROOT" -type f -name 'libroot.so' -print -quit | grep -q .
}

if ! valid_toolchain; then
  if ! command -v sudo >/dev/null 2>&1; then
    echo "ERROR: sudo is required to install Haiku cross-tool build prerequisites" >&2
    exit 1
  fi
  sudo apt-get update -y
  sudo apt-get install -y --no-install-recommends \
    autoconf automake bison bzip2 ca-certificates cmake curl file flex g++ gawk git \
    libtool-bin make nasm pkg-config python3 texinfo wget xz-utils zlib1g-dev

  rm -rf "$HAIKU" "$BUILDTOOLS" "$OUTPUT" "$PACKAGE_ROOT" "$ROOT/bin"
  mkdir -p "$ROOT/bin" "$PACKAGE_ROOT"

  git init -q "$HAIKU"
  git -C "$HAIKU" remote add origin https://github.com/haiku/haiku.git
  git -C "$HAIKU" fetch -q --depth 1 origin "$HAIKU_COMMIT"
  git -C "$HAIKU" checkout -q FETCH_HEAD
  git -C "$HAIKU" apply --check "$PATCH_FILE"
  git -C "$HAIKU" apply "$PATCH_FILE"

  git init -q "$BUILDTOOLS"
  git -C "$BUILDTOOLS" remote add origin https://github.com/haiku/buildtools.git
  git -C "$BUILDTOOLS" fetch -q --depth 1 origin "$BUILDTOOLS_COMMIT"
  git -C "$BUILDTOOLS" checkout -q FETCH_HEAD

  (
    cd "$BUILDTOOLS/jam"
    make -j2
    ./jam0 -sBINDIR="$ROOT/bin" install
  )
  export PATH="$ROOT/bin:$PATH"

  mkdir -p "$OUTPUT" "$SYSROOT/boot"
  ln -sfn "$PACKAGE_ROOT" "$SYSROOT/boot/system"
  (
    cd "$OUTPUT"
    "$HAIKU/configure" \
      --cross-tools-source "$BUILDTOOLS" \
      --build-cross-tools "$HAIKU_ARCH" \
      --no-downloads
    # The source checkout is the complete, fixed Haiku source revision.  Build
    # the two packages needed for the sysroot entirely from that checkout so
    # the build does not depend on the moving HaikuPorts repository metadata.
    # This still produces Haiku's real runtime/development packages; it does
    # not replace missing files with a synthetic sysroot.
    # The fixed source commit is intentionally fetched shallowly and has no
    # hrev tags. Seed the deterministic metadata that Haiku's revision helper
    # consumes so it does not fall back to git-describe. The last-built value
    # matches the checked-out commit, so this exact source revision is kept.
    mkdir -p "$OUTPUT/build"
    printf '%s\n' "$HAIKU_COMMIT" > "$OUTPUT/build/haiku-revision"
    printf '%s\n' "$HAIKU_COMMIT" > "$OUTPUT/build/last-built-revision"
    # Haiku's bootstrap profile deliberately adds -nostdinc while the
    # cross-compiler is being used to build the real headers. The GCC
    # intrinsic headers are still required by those headers (for example
    # limits.h includes float.h), so pass the directories generated by this
    # exact compiler through Jam. These are genuine compiler headers, not
    # synthetic replacements for the Haiku sysroot.
    GCC_INCLUDE_DIR="$("$TOOLBIN/$GNU_TARGET-gcc" -print-file-name=include)"
    GCC_FIXED_INCLUDE_DIR="$("$TOOLBIN/$GNU_TARGET-gcc" -print-file-name=include-fixed)"
    [[ -f "$GCC_INCLUDE_DIR/float.h" ]] || {
      echo "ERROR: Haiku cross GCC intrinsic headers are missing: $GCC_INCLUDE_DIR" >&2
      exit 1
    }
    [[ -d "$GCC_FIXED_INCLUDE_DIR" ]] || {
      echo "ERROR: Haiku cross GCC fixed headers are missing: $GCC_FIXED_INCLUDE_DIR" >&2
      exit 1
    }
    GCC_HEADER_FLAGS="-isystem$GCC_INCLUDE_DIR -isystem$GCC_FIXED_INCLUDE_DIR"
    # The bootstrap profile also adds -nostdinc to C++ compilations.  The
    # compiler's intrinsic headers above are not enough for libstdc++: headers
    # such as <new> and <bits/c++config.h> live in the target compiler's C++
    # include directories and are deliberately not part of the Haiku sysroot.
    # Ask this exact cross g++ for its search list instead of guessing a GCC
    # version or an ABI directory.  Every directory passed below therefore
    # belongs to the pinned Haiku cross toolchain, never to the Ubuntu host.
    CXX_SEARCH_OUTPUT="$(printf '%s\n' '' | "$TOOLBIN/$GNU_TARGET-g++" -E -v -x c++ - 2>&1)"
    CXX_HEADER_FLAGS="$GCC_HEADER_FLAGS"
    CXX_TOOL_ROOT="$OUTPUT/cross-tools-$HAIKU_ARCH"
    CXX_HEADER_COUNT=0
    CXX_BASE_HEADER_DIR=""
    CXX_CONFIG_FOUND=false
    while IFS= read -r CXX_INCLUDE_DIR; do
      [[ -d "$CXX_INCLUDE_DIR" ]] || continue
      case "$CXX_INCLUDE_DIR" in
        "$CXX_TOOL_ROOT"/*/include/c++/*)
          CXX_HEADER_FLAGS+=" -isystem$CXX_INCLUDE_DIR"
          CXX_HEADER_COUNT=$((CXX_HEADER_COUNT + 1))
          if [[ -f "$CXX_INCLUDE_DIR/new" ]]; then
            CXX_BASE_HEADER_DIR="$CXX_INCLUDE_DIR"
          fi
          if [[ -f "$CXX_INCLUDE_DIR/bits/c++config.h" ]]; then
            CXX_CONFIG_FOUND=true
          fi
          ;;
      esac
    done < <(
      printf '%s\n' "$CXX_SEARCH_OUTPUT" |
        awk '
          /#include <\.\.\.> search starts here:/ { in_search = 1; next }
          /^End of search list\./ { in_search = 0 }
          in_search {
            sub(/^[[:space:]]+/, "")
            print
          }
        '
    )
    [[ "$CXX_HEADER_COUNT" -gt 0 && -n "$CXX_BASE_HEADER_DIR" ]] || {
      echo "ERROR: Haiku cross g++ did not expose its libstdc++ headers" >&2
      echo "$CXX_SEARCH_OUTPUT" >&2
      exit 1
    }
    [[ "$CXX_CONFIG_FOUND" == true ]] || {
      echo "ERROR: Haiku cross g++ target-specific bits/c++config.h is missing" >&2
      echo "$CXX_SEARCH_OUTPUT" >&2
      exit 1
    }
    # The profile must be passed through Jam's @profile command-line syntax;
    # setting HAIKU_BUILD_PROFILE with -s is overwritten while Jam parses its
    # targets and silently leaves the build in the regular profile.  The
    # bootstrap profile uses the pinned source-tree HaikuPortsCross packages
    # and still builds the real Haiku runtime/development packages below, so
    # the sysroot does not depend on the moving HaikuPorts repository.
    jam -q -j2 \
      "-sHAIKU_CCFLAGS_${HAIKU_ARCH}=${GCC_HEADER_FLAGS}" \
      "-sHAIKU_C++FLAGS_${HAIKU_ARCH}=${CXX_HEADER_FLAGS}" \
      @bootstrap-raw build haiku.hpkg haiku_devel.hpkg
  )

  PACKAGE_TOOL="$(find "$OUTPUT/objects/linux" -type f -path '*/release/tools/package/package' -perm -111 -print -quit)"
  [[ -x "$PACKAGE_TOOL" ]] || { echo "ERROR: Haiku package extraction tool missing" >&2; exit 1; }
  host_libs="$OUTPUT/objects/linux/lib"
  extract_hpkg() {
    local hpkg="$1"
    [[ -f "$hpkg" ]] || return 0
    LD_LIBRARY_PATH="$host_libs${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
      "$PACKAGE_TOOL" extract -C "$PACKAGE_ROOT" "$hpkg"
  }

  extract_hpkg "$OUTPUT/objects/haiku/$HAIKU_ARCH/packaging/packages/haiku.hpkg"
  extract_hpkg "$OUTPUT/objects/haiku/$HAIKU_ARCH/packaging/packages/haiku_devel.hpkg"
  while IFS= read -r hpkg; do extract_hpkg "$hpkg"; done < <(find "$OUTPUT/download" -type f -name '*.hpkg' -print 2>/dev/null || true)

  if [[ -f "$PACKAGE_ROOT/lib/libgcc_s.so" && -d "$PACKAGE_ROOT/develop/lib" ]]; then
    ln -sfn ../../lib/libgcc_s.so "$PACKAGE_ROOT/develop/lib/libgcc_s.so"
  fi

  valid_toolchain || { echo "ERROR: incomplete Haiku cross-tools/sysroot for $TARGET" >&2; exit 1; }
fi

CC="$TOOLBIN/$GNU_TARGET-gcc"
CXX="$TOOLBIN/$GNU_TARGET-g++"
AR="$TOOLBIN/$GNU_TARGET-ar"
[[ -x "$CC" && -x "$CXX" && -x "$AR" ]] || { echo "ERROR: Haiku GCC tools missing" >&2; exit 1; }

key="${TARGET//-/_}"
key_upper="$(printf '%s' "$key" | tr '[:lower:]' '[:upper:]')"
export "CC_${key}=$CC"
export "CXX_${key}=$CXX"
export "AR_${key}=$AR"
export "CFLAGS_${key}=$CFLAGS_EXTRA"
export "CXXFLAGS_${key}=$CFLAGS_EXTRA"
export "CARGO_TARGET_${key_upper}_LINKER=$CC"
export RUSTFLAGS="${RUSTFLAGS:-} -C linker=$CC"

exec "$@"
