[package]
name = "agena"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Agena command-line application"
autobins = false

[lib]
name = "agena_app"

[[bin]]
name = "agena"
doc = false
path = "src/main.rs"

[dependencies]
agena-api-server = { workspace = true, features = ["jsonrpc"] }
agena-cli = { workspace = true }
agena-domain = { workspace = true }
agena-provider = { workspace = true }
agena-runtime = { workspace = true }
agena-tui = { workspace = true }
agena-tui-app = { workspace = true }
agena-tui-backend = { workspace = true }
agena-tui-platform = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }

[lints]
workspace = true
