[package]
name = "agena-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Agena command-line application"
[[bin]]
name = "agena"
doc = false
path = "src/main.rs"

[dependencies]
agena = { workspace = true }
agena-api-server = { workspace = true, features = ["jsonrpc"] }
agena-tui = { path = "../agena-tui" }
async-trait = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }

[lints]
workspace = true
