[package]
name = "agena-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Agena command-line application"

[[bin]]
name = "agena"
doc = false
path = "src/main.rs"

[dependencies]
agena = { path = "../../crates/agena" }
agena-api-server = { path = "../../crates/agena-api-server", features = ["jsonrpc"] }
agena-otel = { path = "../../crates/agena-otel" }
async-trait = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }

[lints]
workspace = true
