//! UI-only descriptions for bundled tools that build their manifests outside
//! the `#[tool]` documentation attributes.
//!
//! The English contract sent to models remains unchanged. This table fills
//! translated summaries for hand-built command tools and macro-generated web
//! and memory tools whose schemas are stable but whose annotations are split
//! across modules.

use agena_plugin_host::sdk::PluginManifest;

const LOCALES: [&str; 10] = [
    "zh-CN", "zh-TW", "ja-JP", "ko-KR", "fr-FR", "de-DE", "es-ES", "hi-IN", "ar-SA", "pt-BR",
];

/// Enrich a bundled plugin manifest with its UI documentation translations.
/// This runs at the static registration boundary for both manifest discovery
/// and initialization, leaving the model-facing English contract unchanged.
pub(crate) fn localize_bundled_plugin_manifest(manifest: &mut PluginManifest) {
    localize_builtin_tool_docs(manifest);
    crate::plugin_settings_docs::localize_settings_docs(manifest);
    if matches!(manifest.name.as_str(), "chatgpt" | "claude" | "gemini") {
        crate::plugins::provided::provider_tool_docs::localize_provider_manifest(manifest);
    }
}

pub(crate) fn localize_builtin_tool_docs(manifest: &mut PluginManifest) {
    for tool in &mut manifest.tools {
        let summaries = summaries(manifest.name.as_str(), tool.name.as_str());
        for (index, locale) in LOCALES.into_iter().enumerate() {
            let translation = tool.docs.translations.entry(locale.to_owned()).or_default();
            if let Some(summary) = summaries.map(|values| values[index]) {
                translation.summary = Some(summary.to_owned());
            }
            if let Some(help) = help(manifest.name.as_str(), tool.name.as_str(), locale) {
                translation.help = Some(help.to_owned());
            }
        }
    }
}

/// Concise UI translations of the detailed tool guidance. Invocation schemas
/// and the English contracts sent to models remain defined at their sources.
fn help(plugin: &str, tool: &str, locale: &str) -> Option<&'static str> {
    let values = match (plugin, tool) {
        ("commands", "list") => [
            "用 list 发现当前工作区可用的命令包；随后用 get 阅读所选命令的完整说明。",
            "用 list 探索目前工作區可用的命令套件；再用 get 閱讀所選命令的完整說明。",
            "list で利用可能なコマンドパッケージを確認し、get で選んだコマンドの説明を読みます。",
            "list로 사용 가능한 명령 패키지를 확인한 뒤 get으로 선택한 명령의 전체 설명을 읽으세요.",
            "Utilisez list pour découvrir les paquets disponibles, puis get pour lire les instructions complètes d’une commande.",
            "Mit list verfügbare Befehlspakete finden und anschließend mit get die vollständige Anleitung lesen.",
            "Usa list para descubrir los paquetes disponibles y luego get para leer las instrucciones completas de un comando.",
            "list से उपलब्ध कमांड पैकेज खोजें, फिर चुने गए कमांड के पूरे निर्देश get से पढ़ें।",
            "استخدم list لاكتشاف حزم الأوامر المتاحة، ثم get لقراءة تعليمات الأمر كاملة.",
            "Use list para descobrir os pacotes disponíveis e depois get para ler as instruções completas de um comando.",
        ],
        ("commands", "get") => [
            "用命令名称读取完整指令。需要时再用 read_resource 查看命令包附带的资源。",
            "用命令名稱讀取完整指示。需要時再用 read_resource 檢視命令套件附帶的資源。",
            "コマンド名を指定して完全な手順を読みます。必要なら read_resource で同梱リソースを確認します。",
            "명령 이름으로 전체 지침을 읽으세요. 필요하면 read_resource로 패키지 리소스를 확인하세요.",
            "Indiquez le nom de la commande pour lire ses instructions complètes. Consultez les ressources avec read_resource si nécessaire.",
            "Den Befehlsnamen angeben, um die vollständige Anleitung zu lesen. Paketressourcen bei Bedarf mit read_resource öffnen.",
            "Indica el nombre del comando para leer sus instrucciones completas. Consulta los recursos con read_resource si hace falta.",
            "कमांड का नाम देकर पूरे निर्देश पढ़ें। ज़रूरत हो तो पैकेज संसाधन read_resource से खोलें।",
            "حدّد اسم الأمر لقراءة تعليماته كاملة. افتح موارد الحزمة باستخدام read_resource عند الحاجة.",
            "Informe o nome do comando para ler todas as instruções. Se necessário, consulte os recursos do pacote com read_resource.",
        ],
        ("commands", "install") => [
            "仅安装工作区管理目录中的命令文档；不会安装软件或修改外部命令包。",
            "只會安裝工作區管理目錄中的命令文件；不會安裝軟體或修改外部命令套件。",
            "ワークスペース管理対象のコマンド文書だけをインストールします。ソフトウェアや外部パッケージは変更しません。",
            "작업 공간에서 관리하는 명령 문서만 설치합니다. 소프트웨어나 외부 패키지는 변경하지 않습니다.",
            "Installe uniquement les documents de commande gérés par l’espace de travail ; aucun logiciel ni paquet externe n’est modifié.",
            "Installiert nur vom Workspace verwaltete Befehlsdokumente, keine Software oder externen Pakete.",
            "Instala únicamente documentos de comandos gestionados por el espacio de trabajo; no instala software ni modifica paquetes externos.",
            "केवल वर्कस्पेस द्वारा प्रबंधित कमांड दस्तावेज़ स्थापित करें; सॉफ़्टवेयर या बाहरी पैकेज नहीं बदलते।",
            "ثبّت مستندات الأوامر التي يديرها نطاق العمل فقط؛ لا يثبّت برامج ولا يغيّر الحزم الخارجية.",
            "Instala apenas documentos de comando gerenciados pelo workspace; não instala software nem altera pacotes externos.",
        ],
        ("commands", "remove") => [
            "仅移除工作区管理目录中的命令文档；不会删除外部命令包或软件。",
            "只會移除工作區管理目錄中的命令文件；不會刪除外部命令套件或軟體。",
            "ワークスペース管理対象のコマンド文書だけを削除します。外部パッケージやソフトウェアは削除しません。",
            "작업 공간에서 관리하는 명령 문서만 제거합니다. 외부 패키지나 소프트웨어는 삭제하지 않습니다.",
            "Supprime uniquement les documents de commande gérés par l’espace de travail, sans retirer de logiciel ni de paquet externe.",
            "Entfernt nur vom Workspace verwaltete Befehlsdokumente, keine Software oder externen Pakete.",
            "Elimina únicamente documentos de comandos gestionados por el espacio de trabajo; no quita software ni paquetes externos.",
            "केवल वर्कस्पेस द्वारा प्रबंधित कमांड दस्तावेज़ हटाएँ; बाहरी पैकेज या सॉफ़्टवेयर नहीं हटते।",
            "أزِل مستندات الأوامر التي يديرها نطاق العمل فقط؛ لا تحذف البرامج أو الحزم الخارجية.",
            "Remove apenas documentos de comando gerenciados pelo workspace; não remove software nem pacotes externos.",
        ],
        ("content", "read") => [
            "首次读取只传 resource_id；续读时使用 next_position 中的 epoch、sequence 和 offset。has_more 表示仍有内容，gap 表示保留数据缺失；此工具不会等待任务完成。",
            "首次讀取只傳 resource_id；續讀時使用 next_position 中的 epoch、sequence 和 offset。has_more 表示仍有內容，gap 表示保留資料缺失；此工具不會等待工作完成。",
            "初回は resource_id のみ指定します。続きは next_position の epoch・sequence・offset を使います。has_more は続き、gap は保持データの欠落を示し、このツールは完了を待ちません。",
            "처음에는 resource_id만 전달하세요. 이어 읽을 때는 next_position의 epoch, sequence, offset을 사용하세요. has_more는 후속 내용, gap은 보존 데이터 손실을 뜻하며 이 도구는 완료를 기다리지 않습니다.",
            "Au premier appel, indiquez seulement resource_id. Pour continuer, reprenez epoch, sequence et offset dans next_position. has_more signale la suite, gap une perte de rétention ; cet outil n’attend pas la fin d’une tâche.",
            "Beim ersten Lesen nur resource_id angeben. Zum Fortsetzen epoch, sequence und offset aus next_position übernehmen. has_more zeigt weitere Daten, gap einen Aufbewahrungsverlust; das Tool wartet nicht auf den Abschluss.",
            "En la primera lectura indica solo resource_id. Para continuar, usa epoch, sequence y offset de next_position. has_more indica más datos y gap pérdida de retención; esta herramienta no espera a que termine la tarea.",
            "पहली बार केवल resource_id दें। आगे पढ़ने के लिए next_position से epoch, sequence और offset लें। has_more आगे डेटा बताता है, gap संग्रहित डेटा की कमी; यह टूल काम पूरा होने की प्रतीक्षा नहीं करता।",
            "في القراءة الأولى أرسل resource_id فقط. للمتابعة استخدم epoch وsequence وoffset من next_position. تعني has_more وجود المزيد، ويعني gap فقدان بيانات محتفظ بها؛ لا تنتظر هذه الأداة اكتمال المهمة.",
            "Na primeira leitura, informe apenas resource_id. Para continuar, use epoch, sequence e offset de next_position. has_more indica mais dados e gap indica perda de retenção; esta ferramenta não espera a tarefa terminar.",
        ],
        ("fs", "document") => [
            "可提取 PDF、DOCX、PPTX、XLSX 的本地文本；不会安装转换依赖或提供图片、音频转写。空结果可能表示扫描版 PDF 需要 OCR。",
            "可擷取 PDF、DOCX、PPTX、XLSX 的本機文字；不會安裝轉換相依套件，也不提供圖片或音訊轉錄。空結果可能代表掃描版 PDF 需要 OCR。",
            "PDF・DOCX・PPTX・XLSX のローカルテキストを抽出します。変換依存関係は導入せず、画像解析や音声文字起こしも行いません。空の PDF は OCR が必要な場合があります。",
            "PDF, DOCX, PPTX, XLSX의 로컬 텍스트를 추출합니다. 변환 의존성을 설치하거나 이미지·오디오를 전사하지 않습니다. 결과가 비어 있으면 스캔 PDF에 OCR이 필요할 수 있습니다.",
            "Extrait le texte local des PDF, DOCX, PPTX et XLSX. N’installe pas de dépendances et ne transcrit ni images ni audio ; un PDF vide peut nécessiter un OCR.",
            "Extrahiert lokalen Text aus PDF, DOCX, PPTX und XLSX. Installiert keine Abhängigkeiten und transkribiert weder Bilder noch Audio; leere PDFs benötigen eventuell OCR.",
            "Extrae texto local de PDF, DOCX, PPTX y XLSX. No instala dependencias ni transcribe imágenes o audio; un PDF vacío puede necesitar OCR.",
            "PDF, DOCX, PPTX और XLSX से स्थानीय पाठ निकालें। यह निर्भरताएँ स्थापित नहीं करता और छवि या ऑडियो का लिप्यंतरण नहीं करता; खाली PDF को OCR चाहिए हो सकता है।",
            "استخرج النص المحلي من PDF وDOCX وPPTX وXLSX. لا تثبّت تبعيات ولا تفرّغ الصور أو الصوت؛ وقد يحتاج ملف PDF الفارغ إلى OCR.",
            "Extrai texto local de PDF, DOCX, PPTX e XLSX. Não instala dependências nem transcreve imagens ou áudio; um PDF vazio pode precisar de OCR.",
        ],
        ("fs", "read") => [
            "读取文本预览或目录页。行号从 1 开始；长单行可用字节游标续读。二进制文件只返回本地引用；多模态内容用 fs.read_media。",
            "讀取文字預覽或目錄分頁。行號從 1 開始；長單行可用位元組游標續讀。二進位檔只回傳本機參照；多模態內容請用 fs.read_media。",
            "テキストのプレビューやディレクトリ一覧を読みます。行番号は 1 始まりで、長い 1 行はバイトカーソルで続けて読めます。バイナリはローカル参照のみ返すため、メディアには fs.read_media を使います。",
            "텍스트 미리보기나 디렉터리 목록을 읽습니다. 행 번호는 1부터 시작하며 긴 한 줄은 바이트 커서로 이어 읽을 수 있습니다. 바이너리는 로컬 참조만 반환하므로 미디어에는 fs.read_media를 사용하세요.",
            "Lit un aperçu texte ou une page de répertoire. Les lignes commencent à 1 ; les longues lignes se poursuivent avec le curseur d’octets. Les binaires restent des références locales : utilisez fs.read_media pour les médias.",
            "Liest Textvorschauen oder Verzeichnislisten. Zeilen beginnen bei 1; lange Einzelzeilen lassen sich per Bytecursor fortsetzen. Binärdateien liefern nur lokale Verweise; Medien mit fs.read_media öffnen.",
            "Lee vistas previas de texto o páginas de directorio. Las líneas empiezan en 1; las líneas largas se continúan con un cursor de bytes. Los binarios solo devuelven referencias locales; usa fs.read_media para medios.",
            "टेक्स्ट पूर्वावलोकन या निर्देशिका पृष्ठ पढ़ें। पंक्ति क्रमांक 1 से शुरू होते हैं; लंबी पंक्ति को बाइट कर्सर से आगे पढ़ें। बाइनरी केवल स्थानीय संदर्भ देती है; मीडिया के लिए fs.read_media उपयोग करें।",
            "اقرأ معاينة نصية أو صفحة دليل. يبدأ ترقيم الأسطر من 1، ويمكن متابعة السطر الطويل بمؤشر البايتات. تعيد الملفات الثنائية مرجعًا محليًا فقط؛ استخدم fs.read_media للوسائط.",
            "Leia prévias de texto ou páginas de diretório. As linhas começam em 1; linhas longas podem continuar com cursor de bytes. Binários retornam apenas referências locais; use fs.read_media para mídia.",
        ],
        ("fs", "read_media") => [
            "需要查看本地图片、PDF 页面、音频或视频时使用。文件内容会像用户附件一样交给当前模型；图片/PDF 依模型而定，音频需支持的 OpenAI Chat 模型或 Gemini，视频需 Gemini。每个文件最多 20 MiB。",
            "需要檢視本機圖片、PDF 頁面、音訊或影片時使用。檔案內容會像使用者附件一樣交給目前模型；圖片/PDF 視模型而定，音訊需支援的 OpenAI Chat 模型或 Gemini，影片需 Gemini。每個檔案最多 20 MiB。",
            "ローカル画像・PDFページ・音声・動画を確認する場合に使います。ファイル内容をユーザー添付と同様に現在のモデルへ渡します。画像/PDF はモデル依存、音声は対応する OpenAI Chat モデルまたは Gemini、動画は Gemini が必要です。各ファイル最大 20 MiB。",
            "로컬 이미지, PDF 페이지, 오디오 또는 동영상을 볼 때 사용하세요. 파일 내용을 사용자 첨부처럼 현재 모델에 전달합니다. 이미지/PDF는 모델에 따라 다르고, 오디오는 지원되는 OpenAI Chat 모델 또는 Gemini, 동영상은 Gemini가 필요합니다. 파일당 최대 20 MiB입니다.",
            "À utiliser pour examiner une image, une page PDF, un audio ou une vidéo locale. Le contenu est transmis au modèle courant comme une pièce jointe. Images/PDF selon le modèle, audio avec un modèle OpenAI Chat compatible ou Gemini, vidéo avec Gemini. 20 Mio maximum par fichier.",
            "Zum Prüfen lokaler Bilder, PDF-Seiten, Audio- oder Videodateien. Der Inhalt wird wie ein Benutzeranhang an das aktuelle Modell übergeben. Bild/PDF je nach Modell, Audio mit kompatiblem OpenAI-Chat-Modell oder Gemini, Video mit Gemini. Maximal 20 MiB pro Datei.",
            "Úsalo para revisar imágenes, páginas PDF, audio o vídeo locales. El contenido se entrega al modelo actual como un adjunto. Imágenes/PDF según el modelo; audio requiere un modelo OpenAI Chat compatible o Gemini; vídeo requiere Gemini. Máximo 20 MiB por archivo.",
            "स्थानीय छवि, PDF पृष्ठ, ऑडियो या वीडियो देखने के लिए उपयोग करें। सामग्री वर्तमान मॉडल को उपयोगकर्ता अटैचमेंट की तरह दी जाती है। छवि/PDF मॉडल पर निर्भर हैं; ऑडियो के लिए समर्थित OpenAI Chat मॉडल या Gemini और वीडियो के लिए Gemini चाहिए। प्रति फ़ाइल अधिकतम 20 MiB।",
            "استخدمها لفحص صورة أو صفحة PDF أو صوت أو فيديو محلي. يُرسل المحتوى إلى النموذج الحالي كمرفق مستخدم. دعم الصور/PDF حسب النموذج؛ الصوت يحتاج نموذج OpenAI Chat مدعومًا أو Gemini، والفيديو يحتاج Gemini. الحد الأقصى 20 MiB لكل ملف.",
            "Use para examinar imagem, página PDF, áudio ou vídeo local. O conteúdo é enviado ao modelo atual como um anexo do usuário. Imagem/PDF dependem do modelo; áudio exige modelo OpenAI Chat compatível ou Gemini; vídeo exige Gemini. Máximo de 20 MiB por arquivo.",
        ],
        ("fs", "glob") => [
            "先用 glob 定位路径，再读取或编辑。可按文件/目录筛选并分页；扫描有上限，默认遵循隐藏文件与忽略规则。",
            "先用 glob 找出路徑，再讀取或編輯。可依檔案/目錄篩選並分頁；掃描有上限，預設遵循隱藏檔與忽略規則。",
            "glob でパスを絞り込んでから読み取りや編集を行います。ファイル/ディレクトリで絞り込み、ページ分割できます。走査には上限があり、既定では隠しファイルや ignore ルールに従います。",
            "glob으로 경로를 찾은 뒤 읽거나 편집하세요. 파일/디렉터리 필터와 페이지 나누기를 지원합니다. 검색에는 한도가 있으며 기본적으로 숨김·ignore 규칙을 따릅니다.",
            "Repérez les chemins avec glob avant de lire ou modifier. Filtrez fichiers/répertoires et parcourez les pages ; l’analyse est limitée et respecte les règles des fichiers cachés et ignorés.",
            "Mit glob zuerst Pfade finden und danach lesen oder bearbeiten. Dateien/Verzeichnisse lassen sich filtern und seitenweise anzeigen; der Scan ist begrenzt und beachtet standardmäßig Ignore-Regeln.",
            "Busca rutas con glob antes de leer o editar. Filtra archivos/directorios y pagina los resultados; el escaneo tiene límites y respeta las reglas de archivos ocultos e ignorados.",
            "पढ़ने या संपादित करने से पहले glob से पथ खोजें। फ़ाइल/निर्देशिका फ़िल्टर और पृष्ठांकन उपलब्ध हैं; स्कैन सीमित है और डिफ़ॉल्ट रूप से छिपी/अनदेखी फ़ाइलों के नियम मानता है।",
            "ابحث عن المسارات باستخدام glob قبل القراءة أو التحرير. يمكن التصفية حسب الملفات/الأدلة وتقسيم النتائج إلى صفحات؛ الفحص محدود ويتبع قواعد الملفات المخفية والمتجاهلة افتراضيًا.",
            "Use glob para localizar caminhos antes de ler ou editar. Filtre arquivos/diretórios e pagine os resultados; a varredura é limitada e respeita por padrão as regras de arquivos ocultos e ignorados.",
        ],
        ("fs", "grep") => [
            "用正则或固定字符串搜索，可返回匹配行、文件或计数。结果数是全局上限；若扫描不完整，请缩小路径或过滤条件。",
            "用正規表示式或固定字串搜尋，可回傳符合行、檔案或計數。結果數是全域上限；若掃描不完整，請縮小路徑或篩選條件。",
            "正規表現または固定文字列で検索し、一致行・ファイル・件数を返します。結果数は全体の上限です。走査が未完了ならパスや条件を絞ってください。",
            "정규식 또는 고정 문자열로 검색해 일치 행, 파일 또는 개수를 반환합니다. 결과 상한은 전체 기준입니다. 검색이 완료되지 않으면 경로나 필터를 좁히세요.",
            "Recherche par expression régulière ou chaîne fixe et renvoie lignes, fichiers ou nombres. La limite de résultats est globale ; réduisez le chemin ou les filtres si l’analyse est incomplète.",
            "Sucht per Regex oder festem Text und liefert Zeilen, Dateien oder Zählungen. Das Ergebnislimit gilt global; bei unvollständigem Scan Pfad oder Filter eingrenzen.",
            "Busca con regex o texto fijo y devuelve líneas, archivos o recuentos. El límite de resultados es global; reduce la ruta o los filtros si el escaneo queda incompleto.",
            "रेगेक्स या निश्चित पाठ से खोजकर पंक्तियाँ, फ़ाइलें या गणना लौटाएँ। परिणाम सीमा वैश्विक है; अधूरी खोज पर पथ या फ़िल्टर संकरे करें।",
            "ابحث بتعبير نمطي أو نص ثابت لإرجاع الأسطر أو الملفات أو الأعداد. حد النتائج عام؛ ضيّق المسار أو المرشحات إذا لم يكتمل الفحص.",
            "Pesquise por regex ou texto fixo para retornar linhas, arquivos ou contagens. O limite é global; restrinja caminho ou filtros se a varredura ficar incompleta.",
        ],
        ("fs", "apply_patch") => [
            "补丁必须以 `*** Begin Patch` 开始并以 `*** End Patch` 结束，只能使用 Update/Add/Delete File 指令。相对路径始终相对于当前 Agena 工作区。",
            "補丁必須以 `*** Begin Patch` 開始並以 `*** End Patch` 結束，只能使用 Update/Add/Delete File 指示。相對路徑一律相對於目前 Agena 工作區。",
            "パッチは `*** Begin Patch` で始まり `*** End Patch` で終わる必要があります。Update/Add/Delete File のみ使用し、相対パスは現在の Agena ワークスペースを基準にします。",
            "패치는 `*** Begin Patch`로 시작하고 `*** End Patch`로 끝나야 합니다. Update/Add/Delete File 지시자만 사용하며 상대 경로는 현재 Agena 작업 공간 기준입니다.",
            "Le patch doit commencer par `*** Begin Patch` et finir par `*** End Patch`. Utilisez seulement Update/Add/Delete File ; les chemins relatifs partent de l’espace de travail Agena courant.",
            "Der Patch muss mit `*** Begin Patch` beginnen und mit `*** End Patch` enden. Nur Update/Add/Delete File verwenden; relative Pfade beziehen sich auf den aktuellen Agena-Workspace.",
            "El parche debe empezar con `*** Begin Patch` y terminar con `*** End Patch`. Usa solo Update/Add/Delete File; las rutas relativas parten del espacio de trabajo Agena actual.",
            "पैच `*** Begin Patch` से शुरू और `*** End Patch` से समाप्त होना चाहिए। केवल Update/Add/Delete File निर्देश उपयोग करें; सापेक्ष पथ वर्तमान Agena वर्कस्पेस से जुड़ते हैं।",
            "يجب أن يبدأ التصحيح بـ `*** Begin Patch` وينتهي بـ `*** End Patch`. استخدم تعليمات Update/Add/Delete File فقط؛ والمسارات النسبية تبدأ من مساحة عمل Agena الحالية.",
            "O patch deve começar com `*** Begin Patch` e terminar com `*** End Patch`. Use apenas Update/Add/Delete File; caminhos relativos partem do workspace Agena atual.",
        ],
        ("fs", "write") => [
            "创建新文件不需要哈希；替换现有文件时必须传入 fs.stat 返回的 expected_sha256，以避免覆盖已变化的内容。",
            "建立新檔不需要雜湊；替換現有檔案時必須傳入 fs.stat 回傳的 expected_sha256，以避免覆蓋已變更的內容。",
            "新規作成にはハッシュ不要です。既存ファイルの置換では fs.stat の expected_sha256 を指定し、変更済み内容の上書きを防ぎます。",
            "새 파일 생성에는 해시가 필요 없습니다. 기존 파일 교체 시 fs.stat의 expected_sha256를 전달해 변경된 내용을 덮어쓰지 않도록 하세요.",
            "La création ne nécessite pas de hash. Pour remplacer un fichier, fournissez expected_sha256 de fs.stat afin d’éviter d’écraser une version modifiée.",
            "Neue Dateien benötigen keinen Hash. Beim Ersetzen expected_sha256 aus fs.stat angeben, damit geänderte Inhalte nicht überschrieben werden.",
            "Crear archivos nuevos no requiere hash. Al reemplazar uno existente, indica expected_sha256 de fs.stat para no sobrescribir cambios posteriores.",
            "नई फ़ाइल बनाने के लिए हैश नहीं चाहिए। मौजूदा फ़ाइल बदलते समय fs.stat का expected_sha256 दें ताकि बदली हुई सामग्री अनजाने में न मिटे।",
            "لا يلزم تجزئة لإنشاء ملف جديد. عند استبدال ملف قائم، أرسل expected_sha256 من fs.stat لتجنب الكتابة فوق تغييرات أحدث.",
            "Criar um arquivo novo não exige hash. Ao substituir um existente, informe expected_sha256 de fs.stat para evitar sobrescrever alterações recentes.",
        ],
        ("session", "executables") => [
            "检查服务器 PATH 与工作区中的可执行文件；不会安装工具或读取交互式 shell 启动文件。版本探测只对明确提供的 1–8 个名称执行。",
            "檢查伺服器 PATH 與工作區中的可執行檔；不會安裝工具或讀取互動式 shell 啟動檔。版本探測只會對明確提供的 1–8 個名稱執行。",
            "サーバー PATH とワークスペース内の実行可能ファイルを確認します。ツールをインストールせず、対話シェルの起動ファイルも読みません。バージョン確認は指定された 1～8 件だけです。",
            "서버 PATH와 작업 공간의 실행 파일을 확인합니다. 도구를 설치하거나 대화형 셸 시작 파일을 읽지 않습니다. 버전 확인은 지정된 이름 1~8개에만 실행됩니다.",
            "Vérifie les exécutables du PATH serveur et de l’espace de travail, sans installer d’outil ni lire les fichiers de démarrage du shell interactif. Le contrôle de version porte sur 1 à 8 noms fournis.",
            "Prüft ausführbare Dateien im Server-PATH und Workspace, installiert aber nichts und liest keine interaktiven Shell-Startdateien. Versionsprüfungen gelten nur für 1 bis 8 angegebene Namen.",
            "Comprueba ejecutables del PATH del servidor y del espacio de trabajo, sin instalar herramientas ni leer archivos de inicio del shell interactivo. La versión se consulta solo para 1–8 nombres indicados.",
            "सर्वर PATH और वर्कस्पेस के executable जाँचें; टूल स्थापित नहीं करता और इंटरैक्टिव shell startup फ़ाइलें नहीं पढ़ता। संस्करण जाँच केवल दिए गए 1–8 नामों पर चलती है।",
            "افحص الملفات التنفيذية في PATH الخادم ومساحة العمل؛ لا تثبّت أدوات ولا تقرأ ملفات بدء الصدفة التفاعلية. يفحص الإصدارات للأسماء المحددة فقط، من 1 إلى 8.",
            "Verifica executáveis no PATH do servidor e no workspace, sem instalar ferramentas nem ler arquivos de inicialização do shell interativo. A versão é consultada apenas para 1–8 nomes informados.",
        ],
        ("shell", "exec") => [
            "执行命令直到结束。声明实际读写路径与网络目标；timeout_ms 限制运行时间，max_output_bytes 限制预览，完整捕获通过 output_resource 独立读取。",
            "執行命令直到結束。宣告實際讀寫路徑與網路目標；timeout_ms 限制執行時間，max_output_bytes 限制預覽，完整擷取可透過 output_resource 獨立讀取。",
            "コマンドを完了まで実行します。実際の読み書きパスとネットワーク先を宣言してください。timeout_ms は実行時間、max_output_bytes はプレビューを制限し、完全な記録は output_resource から読めます。",
            "명령을 완료될 때까지 실행합니다. 실제 읽기/쓰기 경로와 네트워크 대상을 선언하세요. timeout_ms는 실행 시간, max_output_bytes는 미리보기를 제한하며 전체 캡처는 output_resource에서 읽을 수 있습니다.",
            "Exécute une commande jusqu’à la fin. Déclarez les chemins réellement lus/écrits et les cibles réseau. timeout_ms limite la durée, max_output_bytes l’aperçu ; la capture complète se lit via output_resource.",
            "Führt einen Befehl bis zum Ende aus. Tatsächliche Lese-/Schreibpfade und Netzwerkziele angeben. timeout_ms begrenzt die Laufzeit, max_output_bytes die Vorschau; die vollständige Aufzeichnung steht über output_resource bereit.",
            "Ejecuta un comando hasta que termine. Declara las rutas leídas/escritas y los destinos de red reales. timeout_ms limita la duración y max_output_bytes la vista previa; la captura completa se consulta mediante output_resource.",
            "कमांड पूरा होने तक चलाएँ। वास्तविक पढ़ने/लिखने के पथ और नेटवर्क लक्ष्य घोषित करें। timeout_ms समय और max_output_bytes पूर्वावलोकन सीमित करता है; पूरा आउटपुट output_resource से पढ़ें।",
            "شغّل الأمر حتى يكتمل. صرّح بمسارات القراءة/الكتابة الفعلية وأهداف الشبكة. يحد timeout_ms من المدة وmax_output_bytes من المعاينة؛ ويمكن قراءة الالتقاط الكامل عبر output_resource.",
            "Execute um comando até terminar. Declare os caminhos realmente lidos/escritos e os destinos de rede. timeout_ms limita a duração e max_output_bytes a prévia; a captura completa fica disponível por output_resource.",
        ],
        ("shell", "logs") => [
            "按显式游标重放 shell 输出；续读时同时传 last_seq 与 next_event_offset。读取新输出通常用 shell.read，不要轮询等待后台任务。",
            "依明確游標重播 shell 輸出；續讀時同時傳入 last_seq 與 next_event_offset。讀取新輸出通常用 shell.read，不要輪詢等待背景工作。",
            "明示カーソルから shell 出力を再生します。続きには last_seq と next_event_offset の両方を渡してください。新着出力には通常 shell.read を使い、完了待ちのポーリングはしません。",
            "명시적 커서부터 shell 출력을 재생합니다. 이어 읽을 때 last_seq와 next_event_offset을 함께 전달하세요. 새 출력은 보통 shell.read로 읽고 완료를 폴링해 기다리지 마세요.",
            "Rejoue la sortie shell depuis un curseur explicite. Pour reprendre, transmettez last_seq et next_event_offset. Utilisez plutôt shell.read pour le nouveau contenu et ne sondez pas pour attendre la fin.",
            "Gibt Shell-Ausgabe ab einem expliziten Cursor erneut aus. Zum Fortsetzen last_seq und next_event_offset gemeinsam übergeben. Neue Ausgabe normalerweise mit shell.read lesen; nicht auf den Abschluss pollen.",
            "Reproduce la salida shell desde un cursor explícito. Para continuar, pasa last_seq y next_event_offset juntos. Usa normalmente shell.read para lo nuevo y no consultes repetidamente para esperar.",
            "स्पष्ट कर्सर से shell आउटपुट दोबारा पढ़ें। आगे जारी रखने के लिए last_seq और next_event_offset दोनों दें। नए आउटपुट के लिए shell.read उपयोग करें; समाप्ति के लिए बार-बार जाँच न करें।",
            "أعد تشغيل مخرجات shell من مؤشر صريح. للمتابعة أرسل last_seq وnext_event_offset معًا. استخدم shell.read للمخرجات الجديدة ولا تستطلع انتظارًا للاكتمال.",
            "Reproduza a saída shell a partir de um cursor explícito. Para continuar, envie last_seq e next_event_offset juntos. Use shell.read para novas saídas e não consulte repetidamente para aguardar.",
        ],
        ("shell", "open") => [
            "打开持久交互式 shell/PTY。启动确认后返回 process_id；用 shell.read 与 shell.write 继续交互，静默或提示符不代表进程已退出。",
            "開啟持續互動式 shell/PTY。確認啟動後回傳 process_id；用 shell.read 與 shell.write 繼續互動，靜默或提示字元不代表程序已結束。",
            "永続する対話型 shell/PTY を開きます。起動確認後に process_id を返します。shell.read と shell.write で続けて操作し、無出力やプロンプトを終了と判断しないでください。",
            "지속형 대화형 shell/PTY를 엽니다. 시작이 확인된 뒤 process_id를 반환합니다. shell.read와 shell.write로 계속 상호작용하고 출력이 없거나 프롬프트가 보인다고 종료로 판단하지 마세요.",
            "Ouvre un shell/PTY interactif persistant et renvoie process_id après confirmation du démarrage. Continuez avec shell.read et shell.write ; le silence ou une invite ne signifie pas la fin.",
            "Öffnet eine dauerhafte interaktive Shell/PTY und liefert process_id nach bestätigtem Start. Mit shell.read und shell.write fortfahren; Stille oder Prompt bedeuten nicht, dass der Prozess beendet ist.",
            "Abre un shell/PTY interactivo persistente y devuelve process_id tras confirmar el inicio. Continúa con shell.read y shell.write; el silencio o un prompt no indican que haya terminado.",
            "स्थायी इंटरैक्टिव shell/PTY खोलें। शुरू होने की पुष्टि के बाद process_id मिलता है। shell.read और shell.write से जारी रखें; चुप्पी या prompt का अर्थ समाप्ति नहीं है।",
            "افتح shell/PTY تفاعلية مستمرة وأعد process_id بعد تأكيد البدء. تابع عبر shell.read وshell.write؛ لا يعني الصمت أو ظهور المحث انتهاء العملية.",
            "Abra um shell/PTY interativo persistente e retorne process_id após confirmar a inicialização. Continue com shell.read e shell.write; silêncio ou prompt não significam que terminou.",
        ],
        ("shell", "read") => [
            "读取自上次游标后的有限输出；省略 since_seq 可自动消费新内容。PTY 才能包含屏幕快照。wait_ms 只等待输出，不等待进程完成。",
            "讀取上次游標之後的有限輸出；省略 since_seq 可自動消費新內容。只有 PTY 能包含畫面快照。wait_ms 只等待輸出，不等待程序完成。",
            "前回カーソル以降の出力を上限付きで読みます。since_seq を省略すると新着を自動消費します。画面スナップショットは PTY のみです。wait_ms は出力を待つもので、終了待ちではありません。",
            "이전 커서 이후의 제한된 출력을 읽습니다. since_seq를 생략하면 새 출력을 자동 소비합니다. 화면 스냅샷은 PTY에서만 제공됩니다. wait_ms는 출력만 기다리며 프로세스 완료를 기다리지 않습니다.",
            "Lit la sortie limitée depuis le dernier curseur. Sans since_seq, consomme automatiquement le nouveau contenu. La capture d’écran est réservée aux PTY. wait_ms attend une sortie, pas la fin du processus.",
            "Liest begrenzte Ausgabe ab dem letzten Cursor. Ohne since_seq wird Neues automatisch konsumiert. Bildschirmaufnahmen gibt es nur bei PTYs. wait_ms wartet auf Ausgabe, nicht auf das Prozessende.",
            "Lee una salida limitada desde el cursor anterior. Sin since_seq consume automáticamente lo nuevo. La captura de pantalla solo está disponible en PTY. wait_ms espera salida, no el fin del proceso.",
            "पिछले कर्सर से सीमित आउटपुट पढ़ें। since_seq छोड़ने पर नया आउटपुट अपने-आप लिया जाता है। स्क्रीन स्नैपशॉट केवल PTY में उपलब्ध है। wait_ms आउटपुट की प्रतीक्षा करता है, प्रक्रिया के अंत की नहीं।",
            "اقرأ مخرجات محدودة منذ المؤشر السابق. عند حذف since_seq تُستهلك المخرجات الجديدة تلقائيًا. لقطة الشاشة متاحة في PTY فقط. ينتظر wait_ms المخرجات لا انتهاء العملية.",
            "Leia uma saída limitada desde o cursor anterior. Sem since_seq, o novo conteúdo é consumido automaticamente. A captura de tela só existe em PTY. wait_ms aguarda saída, não o fim do processo.",
        ],
        ("shell", "signal") => [
            "interrupt 中断前台进程但保留 shell；terminate 会清理后结束剩余任务，kill 会跳过宽限期。仅限当前会话/工作区拥有的进程。",
            "interrupt 會中斷前景程序但保留 shell；terminate 會清理後結束剩餘工作，kill 則跳過寬限期。僅限目前工作階段/工作區擁有的程序。",
            "interrupt は shell を保ったまま前景プロセスを中断します。terminate は猶予付きで終了し残存ジョブを停止、kill は猶予を省略します。所有するセッション/ワークスペースが必要です。",
            "interrupt는 shell을 유지하며 전경 프로세스를 중단합니다. terminate는 정리 후 남은 작업을 종료하고 kill은 유예 시간을 건너뜁니다. 소유한 세션/작업 공간에서만 사용할 수 있습니다.",
            "interrupt interrompt le processus au premier plan sans fermer le shell. terminate nettoie puis arrête les tâches restantes ; kill supprime le délai de grâce. Réservé à la session/espace propriétaire.",
            "interrupt unterbricht den Vordergrundprozess, ohne die Shell zu schließen. terminate bereinigt und beendet übrige Jobs; kill überspringt die Schonfrist. Nur für die eigene Sitzung/den eigenen Workspace.",
            "interrupt interrumpe el proceso en primer plano sin cerrar el shell. terminate limpia y detiene los trabajos restantes; kill omite la espera. Requiere la sesión/espacio propietario.",
            "interrupt shell बंद किए बिना foreground प्रक्रिया रोकता है। terminate सफ़ाई करके बाकी jobs समाप्त करता है; kill प्रतीक्षा अवधि छोड़ देता है। केवल स्वामित्व वाले सत्र/वर्कस्पेस में उपयोग करें।",
            "يقاطع interrupt العملية الأمامية دون إغلاق shell. ينظف terminate ثم ينهي المهام المتبقية، بينما يتجاوز kill مهلة السماح. يتطلب ملكية الجلسة/مساحة العمل.",
            "interrupt interrompe o processo em primeiro plano sem fechar o shell. terminate limpa e encerra os trabalhos restantes; kill ignora a espera. Exige a sessão/workspace proprietário.",
        ],
        ("shell", "spawn") => [
            "以关闭的 stdin 启动后台进程，确认启动并注册后才返回。完成或失败会通知；用 shell.read 查看输出，不要轮询等待。",
            "以關閉的 stdin 啟動背景程序，確認啟動並註冊後才回傳。完成或失敗會通知；用 shell.read 查看輸出，不要輪詢等待。",
            "stdin を閉じてバックグラウンドプロセスを起動し、登録確認後に返します。完了や失敗は通知されます。出力確認には shell.read を使い、完了待ちのポーリングはしません。",
            "stdin을 닫은 상태로 백그라운드 프로세스를 시작하고 등록 확인 후 반환합니다. 완료나 실패는 알림으로 전달됩니다. 출력은 shell.read로 확인하고 완료를 폴링해 기다리지 마세요.",
            "Lance un processus en arrière-plan avec stdin fermé et ne renvoie qu’après confirmation du démarrage. La fin ou l’échec est notifié ; utilisez shell.read au lieu de sonder.",
            "Startet einen Hintergrundprozess mit geschlossenem stdin und kehrt erst nach bestätigter Registrierung zurück. Abschluss oder Fehler wird gemeldet; Ausgabe mit shell.read lesen, nicht pollen.",
            "Inicia un proceso en segundo plano con stdin cerrado y solo devuelve tras confirmar el registro. El fin o error se notifica; consulta la salida con shell.read, sin sondear.",
            "बंद stdin के साथ पृष्ठभूमि प्रक्रिया शुरू करें और पंजीकरण पुष्ट होने पर लौटें। समाप्ति या विफलता की सूचना मिलती है; आउटपुट shell.read से देखें, बार-बार जाँच न करें।",
            "ابدأ عملية خلفية مع إغلاق stdin ولا تعد إلا بعد تأكيد التسجيل. يُرسل إشعار عند الانتهاء أو الفشل؛ اقرأ المخرجات عبر shell.read ولا تستطلع انتظارًا.",
            "Inicie um processo em segundo plano com stdin fechado e retorne após confirmar o registro. O término ou falha gera aviso; consulte a saída com shell.read, sem sondagens.",
        ],
        ("shell", "watch") => [
            "为新进程绑定或更新同一进程的通知策略，不会启动第二个命令。通知过滤不影响原始输出捕获；用 shell.read 查看并用 shell.stop 清理。",
            "為新程序綁定或更新同一程序的通知策略，不會啟動第二個命令。通知篩選不影響原始輸出擷取；用 shell.read 查看並用 shell.stop 清理。",
            "新規プロセスに通知条件を設定するか既存プロセスの条件を更新します。別のコマンドは起動しません。通知フィルターは生出力の記録に影響しません。shell.read で確認し shell.stop で停止します。",
            "새 프로세스에 알림 정책을 설정하거나 기존 프로세스의 정책을 바꿉니다. 두 번째 명령은 실행하지 않습니다. 알림 필터는 원시 출력 캡처에 영향을 주지 않습니다. shell.read로 확인하고 shell.stop으로 정리하세요.",
            "Associe ou remplace une politique de notification sur un processus, sans lancer une seconde commande. Les filtres d’alerte ne filtrent pas la capture brute. Lisez avec shell.read et arrêtez avec shell.stop.",
            "Bindet eine Benachrichtigungsregel an einen neuen oder bestehenden Prozess, ohne einen zweiten Befehl zu starten. Filter ändern nicht die Rohdatenerfassung. Mit shell.read lesen und mit shell.stop bereinigen.",
            "Asocia o actualiza avisos de un proceso sin iniciar otro comando. Los filtros de notificación no filtran la captura sin procesar. Lee con shell.read y limpia con shell.stop.",
            "नई प्रक्रिया पर सूचना नीति बाँधें या मौजूदा प्रक्रिया की नीति बदलें; दूसरा कमांड शुरू नहीं होता। सूचना फ़िल्टर कच्चे आउटपुट कैप्चर को नहीं रोकते। shell.read से पढ़ें और shell.stop से साफ़ करें।",
            "اربط سياسة إشعار بعملية جديدة أو حدّثها لعملية قائمة دون تشغيل أمر آخر. لا تؤثر مرشحات الإشعار في التقاط المخرجات الخام. اقرأ عبر shell.read وأنهِ عبر shell.stop.",
            "Associe ou atualize uma política de aviso em um processo sem iniciar outro comando. Os filtros não afetam a captura bruta. Leia com shell.read e encerre com shell.stop.",
        ],
        ("shell", "write") => [
            "chars 会原样发送，不会去空格或追加换行；需要提交时显式发送回车，发送 Ctrl-C 可中断。部分写入失败时不要盲目重发完整输入。",
            "chars 會原樣傳送，不會去空格或附加換行；需要送出時請明確傳送 Enter，傳送 Ctrl-C 可中斷。部分寫入失敗時不要盲目重送完整輸入。",
            "chars は加工せず送信し、空白除去や改行追加はしません。送信には明示的に Enter を送り、Ctrl-C で中断します。一部書き込み失敗時は入力全体を再送しないでください。",
            "chars는 그대로 전송되며 공백을 제거하거나 줄바꿈을 추가하지 않습니다. 제출하려면 Enter를 명시적으로 보내고, Ctrl-C로 중단하세요. 일부 쓰기 실패 후에는 전체 입력을 무작정 다시 보내지 마세요.",
            "chars est envoyé exactement, sans suppression d’espaces ni ajout de saut de ligne. Envoyez explicitement Entrée pour valider et Ctrl-C pour interrompre. Après une écriture partielle, ne renvoyez pas toute l’entrée à l’aveugle.",
            "chars wird unverändert gesendet, ohne Trimmen oder Zeilenumbruch. Enter muss ausdrücklich gesendet werden; Ctrl-C unterbricht. Nach einem Teilfehler nicht blind die gesamte Eingabe erneut senden.",
            "chars se envía tal cual, sin recortar ni añadir salto de línea. Envía Enter explícitamente para confirmar y Ctrl-C para interrumpir. Si falla parcialmente, no reenvíes todo el texto a ciegas.",
            "chars बिल्कुल वैसा ही भेजा जाता है; spaces नहीं हटते और newline नहीं जुड़ती। सबमिट करने के लिए Enter स्पष्ट रूप से भेजें और Ctrl-C से रोकें। आंशिक विफलता पर पूरा इनपुट अंधाधुंध दोबारा न भेजें।",
            "تُرسل chars كما هي دون حذف مسافات أو إضافة سطر جديد. أرسل Enter صراحةً للتأكيد وCtrl-C للمقاطعة. عند فشل جزئي، لا تعِد إرسال الإدخال كاملًا عشوائيًا.",
            "chars é enviado exatamente, sem remover espaços nem acrescentar nova linha. Envie Enter explicitamente para confirmar e Ctrl-C para interromper. Após falha parcial, não reenvie todo o texto às cegas.",
        ],
        ("tasks", "run") => [
            "将有明确边界的工作委派给子会话，适合独立并行任务或跨文件调查。默认等待结果；run_in_background 会立即返回并在结束时通知。",
            "將界線明確的工作委派給子工作階段，適合獨立並行任務或跨檔案調查。預設等待結果；run_in_background 會立即回傳並在結束時通知。",
            "範囲が明確な作業を子セッションへ委任します。独立した並行作業や複数ファイルの調査に適しています。既定では結果を待ち、run_in_background ならすぐ返って完了時に通知します。",
            "범위가 명확한 작업을 하위 세션에 위임합니다. 독립적인 병렬 작업이나 여러 파일 조사가 적합합니다. 기본값은 결과를 기다리며, run_in_background는 즉시 반환하고 완료 시 알립니다.",
            "Délègue un travail bien délimité à une session enfant, notamment des tâches indépendantes ou une recherche multi-fichiers. Par défaut, attend le résultat ; run_in_background rend la main et notifie à la fin.",
            "Delegiert klar abgegrenzte Arbeit an eine Kind-Sitzung, etwa unabhängige Parallelaufgaben oder Recherche über mehrere Dateien. Standardmäßig wird das Ergebnis abgewartet; run_in_background kehrt sofort zurück und benachrichtigt später.",
            "Delega trabajo bien delimitado a una sesión hija, ideal para tareas paralelas independientes o investigar varios archivos. Por defecto espera el resultado; run_in_background devuelve enseguida y avisa al finalizar.",
            "स्पष्ट सीमा वाला काम child session को सौंपें; स्वतंत्र समानांतर कार्य या कई फ़ाइलें पढ़ने के लिए उपयोगी। डिफ़ॉल्ट रूप से परिणाम की प्रतीक्षा होती है; run_in_background तुरंत लौटकर पूरा होने पर सूचना देता है।",
            "فوّض عملًا محدد النطاق إلى جلسة فرعية، مثل المهام المستقلة المتوازية أو قراءة عدة ملفات. ينتظر افتراضيًا؛ ويعود run_in_background فورًا مع إشعار عند الانتهاء.",
            "Delegue um trabalho bem definido a uma sessão filha, como tarefas paralelas independentes ou leitura de vários arquivos. Por padrão aguarda o resultado; run_in_background retorna logo e avisa quando terminar.",
        ],
        ("web", "fetch") => [
            "抓取网页并读取实际内容；长页面用 page_id 与 next_offset 调用 web.read 续读。检查内容状态与警告后再将文本作为依据。",
            "擷取網頁並讀取實際內容；長頁面用 page_id 與 next_offset 呼叫 web.read 續讀。檢查內容狀態與警告後再將文字作為依據。",
            "ページを取得して実際の内容を読みます。長いページは page_id と next_offset で web.read を使って続けます。内容状態と警告を確認してから根拠として扱います。",
            "페이지를 가져와 실제 내용을 읽습니다. 긴 페이지는 page_id와 next_offset으로 web.read를 호출해 이어 읽으세요. 텍스트를 근거로 사용하기 전에 상태와 경고를 확인하세요.",
            "Récupère une page et son contenu réel. Pour la suite d’une longue page, utilisez web.read avec page_id et next_offset. Vérifiez l’état et les avertissements avant d’utiliser le texte comme preuve.",
            "Ruft eine Seite samt tatsächlichem Inhalt ab. Lange Seiten mit page_id und next_offset über web.read fortsetzen. Status und Warnungen prüfen, bevor der Text als Beleg dient.",
            "Obtiene la página y su contenido real. Continúa páginas largas con web.read, page_id y next_offset. Revisa el estado y las advertencias antes de usar el texto como evidencia.",
            "पृष्ठ की वास्तविक सामग्री प्राप्त करें। लंबे पृष्ठ को page_id और next_offset के साथ web.read से आगे पढ़ें। पाठ को प्रमाण मानने से पहले स्थिति और चेतावनियाँ जाँचें।",
            "اجلب الصفحة ومحتواها الفعلي. تابع الصفحات الطويلة عبر web.read باستخدام page_id وnext_offset. افحص الحالة والتحذيرات قبل استخدام النص كدليل.",
            "Busque a página e seu conteúdo real. Continue páginas longas com web.read, page_id e next_offset. Confira o estado e os avisos antes de usar o texto como evidência.",
        ],
        ("web", "fetch_many") => [
            "并发抓取 1–8 个已知网址；每个网址单独报告状态和错误，单页预览默认最多 4000 字符。长页面用返回的 page_id 续读。",
            "並行擷取 1–8 個已知網址；每個網址分別回報狀態與錯誤，單頁預覽預設最多 4000 個字元。長頁面用回傳的 page_id 續讀。",
            "既知の URL を 1～8 件並行取得します。状態とエラーは URL ごとに返り、各ページの既定プレビューは最大 4000 文字です。長いページは返された page_id から続けて読みます。",
            "알려진 URL 1~8개를 동시에 가져옵니다. 상태와 오류는 URL별로 반환되며 페이지당 기본 미리보기는 최대 4000자입니다. 긴 페이지는 반환된 page_id로 이어 읽으세요.",
            "Récupère en parallèle 1 à 8 URL connues. État et erreur sont propres à chaque URL ; l’aperçu est limité par défaut à 4 000 caractères par page. Continuez avec le page_id renvoyé.",
            "Ruft 1 bis 8 bekannte URLs parallel ab. Status und Fehler gelten je URL; die Vorschau umfasst standardmäßig höchstens 4.000 Zeichen pro Seite. Mit der zurückgegebenen page_id weiterlesen.",
            "Obtiene en paralelo entre 1 y 8 URL conocidas. Cada una devuelve su estado y error; la vista previa predeterminada es de hasta 4000 caracteres por página. Continúa con el page_id devuelto.",
            "1–8 ज्ञात URL समानांतर रूप से प्राप्त करें। हर URL का अपना स्थिति/त्रुटि परिणाम होता है; प्रति पृष्ठ डिफ़ॉल्ट पूर्वावलोकन 4000 अक्षरों तक है। लौटाए गए page_id से आगे पढ़ें।",
            "اجلب 1 إلى 8 عناوين معروفة بالتوازي. لكل عنوان حالة وخطأ مستقلان؛ والمعاينة الافتراضية حتى 4000 حرف لكل صفحة. تابع باستخدام page_id المعاد.",
            "Busque de 1 a 8 URLs conhecidas em paralelo. Cada URL tem estado e erro próprios; a prévia padrão vai até 4.000 caracteres por página. Continue com o page_id retornado.",
        ],
        ("web", "read") => [
            "用 fetch、fetch_many 或 query 返回的 page_id 与 next_offset 读取同一份快照；不会重新抓取。检查 truncated 与 content_status，offset 按 Unicode 字符计数。",
            "用 fetch、fetch_many 或 query 回傳的 page_id 與 next_offset 讀取同一份快照；不會重新擷取。檢查 truncated 與 content_status，offset 以 Unicode 字元計數。",
            "fetch・fetch_many・query が返した page_id と next_offset で同じスナップショットを読みます。再取得は行いません。truncated と content_status を確認し、offset は Unicode 文字数です。",
            "fetch, fetch_many 또는 query에서 받은 page_id와 next_offset으로 동일한 스냅샷을 읽습니다. 다시 가져오지 않습니다. truncated와 content_status를 확인하고 offset은 유니코드 문자 단위입니다.",
            "Lit le même instantané avec page_id et next_offset issus de fetch, fetch_many ou query, sans nouvelle récupération. Vérifiez truncated et content_status ; offset compte les caractères Unicode.",
            "Liest denselben Snapshot mit page_id und next_offset aus fetch, fetch_many oder query, ohne erneuten Abruf. truncated und content_status prüfen; offset zählt Unicode-Zeichen.",
            "Lee la misma instantánea con page_id y next_offset de fetch, fetch_many o query, sin volver a obtenerla. Comprueba truncated y content_status; offset cuenta caracteres Unicode.",
            "fetch, fetch_many या query से मिले page_id और next_offset द्वारा वही स्नैपशॉट पढ़ें; फिर से fetch नहीं होता। truncated और content_status जाँचें; offset Unicode अक्षर गिनता है।",
            "اقرأ اللقطة نفسها باستخدام page_id وnext_offset من fetch أو fetch_many أو query دون إعادة الجلب. افحص truncated وcontent_status؛ يحسب offset أحرف Unicode.",
            "Leia a mesma captura com page_id e next_offset de fetch, fetch_many ou query, sem buscar novamente. Confira truncated e content_status; offset conta caracteres Unicode.",
        ],
        ("web", "query") => [
            "仅搜索 web.crawl 已保存的本地索引，不会发起新网络请求。结果可能过期；需要最新依据时重新抓取来源网址。",
            "只搜尋 web.crawl 已儲存的本機索引，不會發出新的網路請求。結果可能過期；需要最新依據時請重新擷取來源網址。",
            "web.crawl が保存したローカル索引だけを検索し、新しいネットワーク要求は行いません。結果が古い場合があるため、最新性が必要なら元 URL を再取得します。",
            "web.crawl이 저장한 로컬 색인만 검색하며 새 네트워크 요청은 하지 않습니다. 결과가 오래되었을 수 있으므로 최신 근거가 필요하면 원본 URL을 다시 가져오세요.",
            "Recherche uniquement l’index local de web.crawl, sans nouvelle requête réseau. Les résultats peuvent dater ; récupérez l’URL source si la fraîcheur est importante.",
            "Durchsucht nur den lokalen Index aus web.crawl und sendet keine neuen Netzwerkanfragen. Ergebnisse können veraltet sein; bei Bedarf die Quell-URL erneut abrufen.",
            "Busca solo en el índice local de web.crawl, sin solicitudes nuevas. Los resultados pueden estar desactualizados; vuelve a obtener la URL de origen si importa la actualidad.",
            "केवल web.crawl के स्थानीय सूचकांक में खोजें; नया नेटवर्क अनुरोध नहीं होता। परिणाम पुराने हो सकते हैं; ताज़ा प्रमाण चाहिए तो स्रोत URL फिर से प्राप्त करें।",
            "ابحث في الفهرس المحلي الذي أنشأه web.crawl فقط دون طلبات شبكة جديدة. قد تكون النتائج قديمة؛ أعد جلب عنوان المصدر عند الحاجة إلى حداثة المعلومات.",
            "Pesquise apenas no índice local de web.crawl, sem novas requisições. Os resultados podem estar desatualizados; busque a URL de origem novamente se atualidade for importante.",
        ],
        ("web", "crawl") => [
            "按广度优先遍历网站，并受并发、页面数、深度、robots 与 URL 预算限制。只有完整且可读的 2xx 页面会保存；随后用 web.query 搜索。",
            "以廣度優先方式瀏覽網站，並受並行數、頁數、深度、robots 與 URL 預算限制。只有完整且可讀的 2xx 頁面會儲存；之後用 web.query 搜尋。",
            "幅優先でサイトを巡回します。並行数・ページ数・深さ・robots・URL 予算に制限があります。完全で読める 2xx ページのみ保存され、後から web.query で検索できます。",
            "너비 우선으로 사이트를 탐색하며 동시성, 페이지 수, 깊이, robots 및 URL 예산 제한을 따릅니다. 완전하고 읽을 수 있는 2xx 페이지만 저장되며 이후 web.query로 검색할 수 있습니다.",
            "Parcourt le site en largeur avec des limites de concurrence, pages, profondeur, robots et URL. Seules les pages 2xx complètes et lisibles sont stockées ; recherchez-les ensuite avec web.query.",
            "Durchläuft die Website breitensuchend mit Grenzen für Parallelität, Seiten, Tiefe, robots und URLs. Nur vollständige, lesbare 2xx-Seiten werden gespeichert; anschließend mit web.query suchen.",
            "Recorre el sitio en anchura con límites de concurrencia, páginas, profundidad, robots y URL. Solo guarda páginas 2xx completas y legibles; después búscalas con web.query.",
            "साइट को breadth-first तरीके से खोजें; concurrency, पृष्ठ, गहराई, robots और URL बजट सीमित हैं। केवल पूर्ण और पढ़ने योग्य 2xx पृष्ठ सहेजे जाते हैं; बाद में web.query से खोजें।",
            "تصفّح الموقع بعرض أولًا مع حدود للتوازي والصفحات والعمق وrobots وعناوين URL. تُحفظ الصفحات 2xx الكاملة والمقروءة فقط؛ ابحث فيها لاحقًا عبر web.query.",
            "Percorra o site em largura, respeitando limites de concorrência, páginas, profundidade, robots e URLs. Apenas páginas 2xx completas e legíveis são salvas; depois pesquise com web.query.",
        ],
        ("web", "search") => [
            "发现公开网页候选项；事实回答应继续抓取 1–3 个相关网址。摘要只是预览，不是已抓取页面的证据。",
            "尋找公開網頁候選項；回答事實問題時應再擷取 1–3 個相關網址。摘要只是預覽，不是已擷取頁面的證據。",
            "公開ページの候補を探します。事実への回答では関連 URL を 1～3 件取得してください。スニペットはプレビューであり、取得済みページの根拠ではありません。",
            "공개 페이지 후보를 찾습니다. 사실 답변에는 관련 URL 1~3개를 추가로 가져오세요. 스니펫은 미리보기일 뿐 가져온 페이지의 근거가 아닙니다.",
            "Recherche des pages publiques candidates. Pour une réponse factuelle, récupérez ensuite 1 à 3 URL pertinentes. Les extraits sont des aperçus, pas des preuves issues d’une page récupérée.",
            "Findet mögliche öffentliche Seiten. Für Sachantworten anschließend 1 bis 3 relevante URLs abrufen. Snippets sind Vorschauen und keine Belege aus einer abgerufenen Seite.",
            "Encuentra páginas públicas candidatas. Para responder con hechos, obtén después entre 1 y 3 URL relevantes. Los fragmentos son vistas previas, no pruebas de una página obtenida.",
            "सार्वजनिक पृष्ठ खोजें; तथ्यात्मक उत्तर के लिए 1–3 प्रासंगिक URL आगे fetch करें। Snippet केवल पूर्वावलोकन है, प्राप्त पृष्ठ का प्रमाण नहीं।",
            "اعثر على صفحات عامة مرشحة؛ وللإجابات الواقعية اجلب لاحقًا من 1 إلى 3 عناوين مناسبة. المقتطفات معاينات وليست أدلة من صفحة تم جلبها.",
            "Encontre páginas públicas candidatas; para respostas factuais, busque depois de 1 a 3 URLs relevantes. Trechos são prévias, não evidências de uma página obtida.",
        ],
        ("web", "browser_shutdown") => [
            "只关闭当前 Agena 会话拥有的浏览器页面，不会停止共享 Chrome 进程或影响其他会话。",
            "只會關閉目前 Agena 工作階段擁有的瀏覽器頁面，不會停止共用 Chrome 程序或影響其他工作階段。",
            "現在の Agena セッションが所有するページだけを閉じます。共有 Chrome プロセスや他のセッションには影響しません。",
            "현재 Agena 세션이 소유한 페이지만 닫습니다. 공유 Chrome 프로세스나 다른 세션에는 영향을 주지 않습니다.",
            "Ferme uniquement les pages appartenant à la session Agena courante, sans arrêter Chrome partagé ni affecter les autres sessions.",
            "Schließt nur Seiten der aktuellen Agena-Sitzung. Der gemeinsame Chrome-Prozess und andere Sitzungen bleiben unberührt.",
            "Cierra solo las páginas de la sesión actual de Agena. No detiene Chrome compartido ni afecta a otras sesiones.",
            "केवल वर्तमान Agena सत्र के स्वामित्व वाले पृष्ठ बंद करें। साझा Chrome प्रक्रिया या दूसरे सत्र प्रभावित नहीं होते।",
            "أغلق الصفحات التابعة لجلسة Agena الحالية فقط؛ لا توقف Chrome المشترك ولا تؤثر في الجلسات الأخرى.",
            "Fecha apenas as páginas da sessão Agena atual. Não encerra o Chrome compartilhado nem afeta outras sessões.",
        ],
        _ => return None,
    };
    let index = LOCALES.iter().position(|candidate| *candidate == locale)?;
    Some(values[index])
}

fn summaries(plugin: &str, tool: &str) -> Option<[&'static str; 10]> {
    Some(match (plugin, tool) {
        ("commands", "list") => [
            "列出已发现的命令包。",
            "列出已發現的命令套件。",
            "見つかったコマンドパッケージを一覧表示します。",
            "발견된 명령 패키지를 나열합니다.",
            "Lister les paquets de commandes détectés.",
            "Gefundene Befehlspakete auflisten.",
            "Enumera los paquetes de comandos encontrados.",
            "मिले हुए कमांड पैकेज की सूची दिखाएँ।",
            "اعرض حزم الأوامر التي تم العثور عليها.",
            "Lista os pacotes de comandos encontrados.",
        ],
        ("commands", "get") => [
            "读取一个命令包的完整说明。",
            "讀取一個命令套件的完整說明。",
            "コマンドパッケージの説明を全文取得します。",
            "명령 패키지의 전체 지침을 읽습니다.",
            "Lire les instructions complètes d’un paquet de commandes.",
            "Die vollständige Anleitung eines Befehlspakets lesen.",
            "Lee las instrucciones completas de un paquete de comandos.",
            "किसी कमांड पैकेज के पूरे निर्देश पढ़ें।",
            "اقرأ التعليمات الكاملة لحزمة أوامر واحدة.",
            "Lê as instruções completas de um pacote de comandos.",
        ],
        ("commands", "install") => [
            "安装工作区管理的命令包文档。",
            "安裝由工作區管理的命令套件文件。",
            "ワークスペース管理のコマンドパッケージ文書をインストールします。",
            "작업 공간에서 관리하는 명령 패키지 문서를 설치합니다.",
            "Installer un document de paquet de commandes géré par l’espace de travail.",
            "Ein vom Workspace verwaltetes Befehlspaket-Dokument installieren.",
            "Instala un documento de paquete de comandos gestionado por el espacio de trabajo.",
            "वर्कस्पेस द्वारा प्रबंधित कमांड पैकेज दस्तावेज़ स्थापित करें।",
            "ثبّت مستند حزمة أوامر يديره نطاق العمل.",
            "Instala um documento de pacote de comandos gerenciado pelo workspace.",
        ],
        ("commands", "remove") => [
            "移除工作区管理的命令包文档。",
            "移除由工作區管理的命令套件文件。",
            "ワークスペース管理のコマンドパッケージ文書を削除します。",
            "작업 공간에서 관리하는 명령 패키지 문서를 제거합니다.",
            "Supprimer un document de paquet de commandes géré par l’espace de travail.",
            "Ein vom Workspace verwaltetes Befehlspaket-Dokument entfernen.",
            "Elimina un documento de paquete de comandos gestionado por el espacio de trabajo.",
            "वर्कस्पेस द्वारा प्रबंधित कमांड पैकेज दस्तावेज़ हटाएँ।",
            "أزِل مستند حزمة أوامر يديره نطاق العمل.",
            "Remove um documento de pacote de comandos gerenciado pelo workspace.",
        ],
        ("commands", "read_resource") => [
            "读取命令包中受限大小的 UTF-8 资源。",
            "讀取命令套件中大小受限的 UTF-8 資源。",
            "コマンドパッケージ内のサイズ制限付き UTF-8 リソースを読み込みます。",
            "명령 패키지에 포함된 크기 제한 UTF-8 리소스를 읽습니다.",
            "Lire une ressource UTF-8 de taille limitée contenue dans un paquet.",
            "Eine größenbegrenzte UTF-8-Ressource aus einem Paket lesen.",
            "Lee un recurso UTF-8 de tamaño limitado incluido en un paquete.",
            "पैकेज के भीतर सीमित आकार वाला UTF-8 संसाधन पढ़ें।",
            "اقرأ مورد UTF-8 محدود الحجم من داخل الحزمة.",
            "Lê um recurso UTF-8 com tamanho limitado dentro de um pacote.",
        ],
        ("commands", "refresh") => [
            "重新扫描文件系统中的命令包并返回目录版本。",
            "重新掃描檔案系統中的命令套件並回傳目錄版本。",
            "ファイルシステム上のコマンドパッケージを再スキャンし、カタログの世代を返します。",
            "파일 시스템의 명령 패키지를 다시 검색하고 카탈로그 세대를 반환합니다.",
            "Reparcourir les paquets de commandes du système de fichiers et renvoyer la version du catalogue.",
            "Befehlspakete im Dateisystem erneut einlesen und die Katalogversion zurückgeben.",
            "Vuelve a explorar los paquetes de comandos del sistema de archivos y devuelve la versión del catálogo.",
            "फ़ाइल सिस्टम के कमांड पैकेज फिर से स्कैन करें और कैटलॉग संस्करण लौटाएँ।",
            "أعِد فحص حزم الأوامر في نظام الملفات وأعد إصدار الفهرس.",
            "Examina novamente os pacotes de comandos no sistema de arquivos e retorna a versão do catálogo.",
        ],
        ("memory", "search") => [
            "搜索持久记忆记录。",
            "搜尋持久記憶記錄。",
            "永続メモリの記録を検索します。",
            "영구 메모리 기록을 검색합니다.",
            "Rechercher dans les mémoires persistantes.",
            "Dauerhafte Erinnerungseinträge durchsuchen.",
            "Busca en los recuerdos persistentes.",
            "स्थायी मेमोरी रिकॉर्ड खोजें।",
            "ابحث في سجلات الذاكرة الدائمة.",
            "Pesquisa registros de memória persistente.",
        ],
        ("memory", "get") => [
            "读取一条持久记忆记录。",
            "讀取一筆持久記憶記錄。",
            "永続メモリの記録を 1 件読み込みます。",
            "영구 메모리 기록 하나를 읽습니다.",
            "Lire une entrée de mémoire persistante.",
            "Einen dauerhaften Erinnerungseintrag lesen.",
            "Lee un recuerdo persistente.",
            "एक स्थायी मेमोरी रिकॉर्ड पढ़ें।",
            "اقرأ سجلًا واحدًا من الذاكرة الدائمة.",
            "Lê um registro de memória persistente.",
        ],
        ("memory", "list") => [
            "列出持久记忆记录。",
            "列出持久記憶記錄。",
            "永続メモリの記録を一覧表示します。",
            "영구 메모리 기록을 나열합니다.",
            "Lister les entrées de mémoire persistante.",
            "Dauerhafte Erinnerungseinträge auflisten.",
            "Enumera los recuerdos persistentes.",
            "स्थायी मेमोरी रिकॉर्ड की सूची दिखाएँ।",
            "اعرض سجلات الذاكرة الدائمة.",
            "Lista os registros de memória persistente.",
        ],
        ("memory", "write") => [
            "写入一条持久记忆记录。",
            "寫入一筆持久記憶記錄。",
            "永続メモリの記録を 1 件保存します。",
            "영구 메모리 기록 하나를 저장합니다.",
            "Enregistrer une entrée de mémoire persistante.",
            "Einen dauerhaften Erinnerungseintrag speichern.",
            "Guarda un recuerdo persistente.",
            "एक स्थायी मेमोरी रिकॉर्ड सहेजें।",
            "احفظ سجلًا واحدًا في الذاكرة الدائمة.",
            "Grava um registro de memória persistente.",
        ],
        ("memory", "delete") => [
            "删除一条持久记忆记录。",
            "刪除一筆持久記憶記錄。",
            "永続メモリの記録を 1 件削除します。",
            "영구 메모리 기록 하나를 삭제합니다.",
            "Supprimer une entrée de mémoire persistante.",
            "Einen dauerhaften Erinnerungseintrag löschen.",
            "Elimina un recuerdo persistente.",
            "एक स्थायी मेमोरी रिकॉर्ड हटाएँ।",
            "احذف سجلًا واحدًا من الذاكرة الدائمة.",
            "Exclui um registro de memória persistente.",
        ],
        ("web", "fetch") => [
            "抓取一个网页并查看其实际内容。",
            "擷取一個網頁並檢視其實際內容。",
            "ウェブページを 1 件取得して実際の内容を確認します。",
            "웹 페이지 하나를 가져와 실제 내용을 확인합니다.",
            "Récupérer une page Web et consulter son contenu réel.",
            "Eine Webseite abrufen und ihren tatsächlichen Inhalt prüfen.",
            "Obtiene una página web y muestra su contenido real.",
            "एक वेब पृष्ठ प्राप्त कर उसकी वास्तविक सामग्री देखें।",
            "اجلب صفحة ويب واحدة وافحص محتواها الفعلي.",
            "Busca uma página da web e mostra seu conteúdo real.",
        ],
        ("web", "fetch_many") => [
            "并发读取多个互不依赖的网页。",
            "並行讀取多個互不相依的網頁。",
            "複数の独立したウェブページを並行して取得します。",
            "서로 독립적인 여러 웹 페이지를 동시에 읽습니다.",
            "Lire en parallèle plusieurs pages Web indépendantes.",
            "Mehrere unabhängige Webseiten parallel abrufen.",
            "Lee en paralelo varias páginas web independientes.",
            "कई स्वतंत्र वेब पृष्ठों को समानांतर रूप से पढ़ें।",
            "اقرأ عدة صفحات ويب مستقلة بالتوازي.",
            "Lê várias páginas da web independentes em paralelo.",
        ],
        ("web", "read") => [
            "继续读取不可变的网页快照。",
            "繼續讀取不可變的網頁快照。",
            "変更されない取得済みページのスナップショットを続けて読みます。",
            "변경되지 않는 가져온 페이지 스냅샷을 이어서 읽습니다.",
            "Poursuivre la lecture d’un instantané immuable de page récupérée.",
            "Einen unveränderlichen Snapshot einer abgerufenen Seite weiterlesen.",
            "Continúa leyendo una instantánea inmutable de una página obtenida.",
            "प्राप्त पृष्ठ के अपरिवर्तनीय स्नैपशॉट को आगे पढ़ें।",
            "تابع قراءة لقطة ثابتة لصفحة تم جلبها.",
            "Continua a leitura de uma captura imutável de página obtida.",
        ],
        ("web", "query") => [
            "在本地爬取的网页中查找依据并获取可读快照。",
            "在本機爬取的網頁中尋找依據並取得可讀快照。",
            "ローカルにクロールしたページから根拠を探し、読みやすいスナップショットを取得します。",
            "로컬에서 크롤링한 페이지에서 근거를 찾고 읽을 수 있는 스냅샷을 가져옵니다.",
            "Trouver des éléments probants dans les pages explorées localement et obtenir des instantanés lisibles.",
            "Belege in lokal gecrawlten Seiten finden und lesbare Snapshots abrufen.",
            "Busca pruebas en páginas rastreadas localmente y obtiene instantáneas legibles.",
            "स्थानीय रूप से क्रॉल किए गए पृष्ठों में प्रमाण खोजें और पढ़ने योग्य स्नैपशॉट लें।",
            "ابحث عن أدلة في الصفحات التي زحف إليها محليًا واحصل على لقطات مقروءة.",
            "Encontra evidências em páginas rastreadas localmente e obtém capturas legíveis.",
        ],
        ("web", "crawl") => [
            "爬取网站并在本地缓存索引页面。",
            "爬取網站並在本機快取已索引頁面。",
            "サイトをクロールし、インデックス済みページをローカルに保存します。",
            "사이트를 크롤링하고 색인된 페이지를 로컬에 저장합니다.",
            "Explorer un site et mettre en cache localement les pages indexées.",
            "Eine Website crawlen und indexierte Seiten lokal zwischenspeichern.",
            "Rastrea un sitio y guarda localmente en caché las páginas indexadas.",
            "साइट क्रॉल करें और अनुक्रमित पृष्ठों को स्थानीय कैश में रखें।",
            "ازحف موقعًا واحفظ الصفحات المفهرسة مؤقتًا محليًا.",
            "Rastreia um site e armazena localmente as páginas indexadas em cache.",
        ],
        ("web", "search") => [
            "查找可供后续抓取的公开网页。",
            "尋找可供後續擷取的公開網頁。",
            "後で取得する公開ウェブページを検索します。",
            "나중에 가져올 공개 웹 페이지를 검색합니다.",
            "Rechercher des pages Web publiques à récupérer ensuite.",
            "Öffentliche Webseiten zum späteren Abruf finden.",
            "Busca páginas web públicas para obtenerlas después.",
            "बाद में प्राप्त करने के लिए सार्वजनिक वेब पृष्ठ खोजें।",
            "ابحث عن صفحات ويب عامة لجلبها لاحقًا.",
            "Busca páginas públicas da web para obter depois.",
        ],
        ("web", "browser_open") => [
            "在受管浏览器会话中打开网页。",
            "在受管理的瀏覽器工作階段中開啟網頁。",
            "管理対象のブラウザーセッションでページを開きます。",
            "관리되는 브라우저 세션에서 페이지를 엽니다.",
            "Ouvrir une page dans une session de navigateur gérée.",
            "Eine Seite in einer verwalteten Browsersitzung öffnen.",
            "Abre una página en una sesión de navegador gestionada.",
            "प्रबंधित ब्राउज़र सत्र में पृष्ठ खोलें।",
            "افتح صفحة في جلسة متصفح مُدارة.",
            "Abre uma página em uma sessão de navegador gerenciada.",
        ],
        ("web", "browser_list") => [
            "列出受管浏览器中已打开的页面目标。",
            "列出受管理瀏覽器中已開啟的頁面目標。",
            "管理対象ブラウザーで開いているページを一覧表示します。",
            "관리되는 브라우저에서 열린 페이지 대상을 나열합니다.",
            "Lister les pages ouvertes dans le navigateur géré.",
            "Geöffnete Seiten im verwalteten Browser auflisten.",
            "Enumera las páginas abiertas en el navegador gestionado.",
            "प्रबंधित ब्राउज़र में खुले पृष्ठों की सूची दिखाएँ।",
            "اعرض الصفحات المفتوحة في المتصفح المُدار.",
            "Lista as páginas abertas no navegador gerenciado.",
        ],
        ("web", "browser_close") => [
            "关闭受管浏览器中的一个页面。",
            "關閉受管理瀏覽器中的一個頁面。",
            "管理対象ブラウザーのページを 1 件閉じます。",
            "관리되는 브라우저에서 페이지 하나를 닫습니다.",
            "Fermer une page dans le navigateur géré.",
            "Eine Seite im verwalteten Browser schließen.",
            "Cierra una página del navegador gestionado.",
            "प्रबंधित ब्राउज़र में एक पृष्ठ बंद करें।",
            "أغلق صفحة واحدة في المتصفح المُدار.",
            "Fecha uma página no navegador gerenciado.",
        ],
        ("web", "browser_shutdown") => [
            "关闭当前 Agena 会话拥有的浏览器页面。",
            "關閉目前 Agena 工作階段擁有的瀏覽器頁面。",
            "現在の Agena セッションが所有するブラウザーページを閉じます。",
            "현재 Agena 세션이 소유한 브라우저 페이지를 닫습니다.",
            "Fermer les pages du navigateur appartenant à la session Agena actuelle.",
            "Browserseiten schließen, die zur aktuellen Agena-Sitzung gehören.",
            "Cierra las páginas del navegador que pertenecen a la sesión actual de Agena.",
            "वर्तमान Agena सत्र के स्वामित्व वाले ब्राउज़र पृष्ठ बंद करें।",
            "أغلق صفحات المتصفح التابعة لجلسة Agena الحالية.",
            "Fecha as páginas do navegador pertencentes à sessão atual do Agena.",
        ],
        ("web", "browser_snapshot") => [
            "查看浏览器会话中的可见文本和交互元素。",
            "檢視瀏覽器工作階段中的可見文字與互動元素。",
            "ブラウザーセッションに表示されたテキストと操作可能な要素を確認します。",
            "브라우저 세션에 보이는 텍스트와 상호작용 요소를 확인합니다.",
            "Inspecter le texte visible et les éléments interactifs d’une session de navigateur.",
            "Sichtbaren Text und interaktive Elemente einer Browsersitzung prüfen.",
            "Examina el texto visible y los elementos interactivos de una sesión del navegador.",
            "ब्राउज़र सत्र में दिखने वाला पाठ और इंटरैक्टिव तत्व देखें।",
            "افحص النص الظاهر والعناصر التفاعلية في جلسة المتصفح.",
            "Inspeciona o texto visível e os elementos interativos de uma sessão do navegador.",
        ],
        ("web", "browser_click") => [
            "点击由 CSS 选择器或最新快照引用标识的浏览器元素。",
            "點擊由 CSS 選擇器或最新快照參照所指定的瀏覽器元素。",
            "CSS セレクターまたは最新スナップショットの参照で指定した要素をクリックします。",
            "CSS 선택자나 최신 스냅샷 참조로 지정한 브라우저 요소를 클릭합니다.",
            "Cliquer sur un élément du navigateur désigné par un sélecteur CSS ou la dernière référence de capture.",
            "Ein über CSS-Selektor oder den neuesten Snapshot-Verweis ausgewähltes Browserelement anklicken.",
            "Hace clic en un elemento indicado por un selector CSS o la referencia de la instantánea más reciente.",
            "CSS चयनकर्ता या नवीनतम स्नैपशॉट संदर्भ से चुने गए ब्राउज़र तत्व पर क्लिक करें।",
            "انقر عنصرًا حدده محدد CSS أو مرجع أحدث لقطة.",
            "Clica em um elemento indicado por um seletor CSS ou pela referência da captura mais recente.",
        ],
        ("web", "browser_type") => [
            "在指定的浏览器输入框中填写内容，并可选择按回车。",
            "在指定的瀏覽器輸入欄位中填入內容，並可選擇按下 Enter。",
            "指定したブラウザー入力欄に入力し、必要に応じて Enter を押します。",
            "지정한 브라우저 입력란에 입력하고 필요하면 Enter를 누릅니다.",
            "Remplir un champ du navigateur et, si besoin, appuyer sur Entrée.",
            "Ein ausgewähltes Browserfeld ausfüllen und optional Enter drücken.",
            "Rellena un campo del navegador y, si se indica, pulsa Intro.",
            "चुने गए ब्राउज़र इनपुट में लिखें और चाहें तो Enter दबाएँ।",
            "املأ حقلًا في المتصفح واضغط Enter عند الحاجة.",
            "Preenche um campo do navegador e, se necessário, pressiona Enter.",
        ],
        ("web", "browser_wait") => [
            "等待页面就绪、指定选择器出现或指定文本可见。",
            "等待頁面就緒、指定選擇器出現或指定文字可見。",
            "ページの準備完了、指定セレクターの出現、または指定テキストの表示を待ちます。",
            "페이지 준비, 지정한 선택자 표시 또는 텍스트가 보일 때까지 기다립니다.",
            "Attendre que la page soit prête, qu’un sélecteur apparaisse ou qu’un texte soit visible.",
            "Auf Seitenbereitschaft, einen Selektor oder sichtbaren Text warten.",
            "Espera a que la página esté lista, aparezca un selector o se vea un texto.",
            "पृष्ठ तैयार होने, चयनकर्ता दिखने या पाठ दिखाई देने तक प्रतीक्षा करें।",
            "انتظر حتى تصبح الصفحة جاهزة أو يظهر محدد أو نص معين.",
            "Aguarda a página ficar pronta, um seletor aparecer ou um texto ficar visível.",
        ],
        ("web", "browser_screenshot") => [
            "截取浏览器页面并作为图片附件返回。",
            "擷取瀏覽器畫面並以圖片附件回傳。",
            "ブラウザー画面を撮影し、画像添付として返します。",
            "브라우저 화면을 캡처해 이미지 첨부로 반환합니다.",
            "Capturer l’écran du navigateur et le renvoyer en pièce jointe.",
            "Einen Browser-Screenshot aufnehmen und als Bildanhang zurückgeben.",
            "Captura la pantalla del navegador y la devuelve como imagen adjunta.",
            "ब्राउज़र का स्क्रीनशॉट लेकर छवि अटैचमेंट के रूप में लौटाएँ।",
            "التقط صورة للشاشة في المتصفح وأعدها كمرفق صورة.",
            "Captura a tela do navegador e retorna como anexo de imagem.",
        ],
        ("web", "browser_download") => [
            "通过受管浏览器会话下载 HTTP(S) 网址并返回本地文件。",
            "透過受管理的瀏覽器工作階段下載 HTTP(S) 網址並回傳本機檔案。",
            "管理対象のブラウザーセッションで HTTP(S) URL をダウンロードし、ローカル成果物を返します。",
            "관리되는 브라우저 세션에서 HTTP(S) URL을 다운로드하고 로컬 파일을 반환합니다.",
            "Télécharger une URL HTTP(S) via le navigateur géré et renvoyer un fichier local.",
            "Eine HTTP(S)-URL über die verwaltete Browsersitzung laden und eine lokale Datei zurückgeben.",
            "Descarga una URL HTTP(S) mediante el navegador gestionado y devuelve un archivo local.",
            "प्रबंधित ब्राउज़र सत्र से HTTP(S) URL डाउनलोड करें और स्थानीय फ़ाइल लौटाएँ।",
            "نزّل عنوان HTTP(S) عبر جلسة المتصفح المُدارة وأعد ملفًا محليًا.",
            "Baixa uma URL HTTP(S) pela sessão de navegador gerenciada e retorna um arquivo local.",
        ],
        _ => return None,
    })
}
