use crossterm::event::{KeyCode as K, KeyEvent};

use super::{
    KeyAction as A, KeyContext, only_alt, only_ctrl, only_shift, unmodified, unmodified_or_shift,
};

pub(super) fn resolve(context: KeyContext, key: KeyEvent) -> Option<A> {
    match context {
        KeyContext::Global => match key.code {
            K::Char('c') if only_ctrl(key) => Some(A::Interrupt),
            K::Char('h') if only_ctrl(key) => Some(A::Help),
            K::Char('\u{0008}') if unmodified(key) => Some(A::Help),
            _ => None,
        },
        KeyContext::Main => match key.code {
            K::Char('/') if unmodified(key) => Some(A::SearchForward),
            K::Char('?') if unmodified_or_shift(key) => Some(A::SearchBackward),
            K::Char('N') if unmodified_or_shift(key) => Some(A::SearchPrevious),
            K::Char('n') if only_ctrl(key) => Some(A::New),
            K::Char('n') if unmodified(key) => Some(A::SearchNext),
            K::Char('r') if unmodified(key) => Some(A::Continue),
            K::Char('U') if unmodified_or_shift(key) => Some(A::OpenUsage),
            _ => None,
        },
        KeyContext::Sessions => match key.code {
            K::Char('1') if unmodified(key) => Some(A::ModeAll),
            K::Char('2') if unmodified(key) => Some(A::ModeRoots),
            K::Char('3') if unmodified(key) => Some(A::ModeSubtree),
            K::Char('m') if unmodified(key) => Some(A::ModeCycle),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Enter if unmodified(key) => Some(A::Open),
            _ => None,
        },
        KeyContext::Transcript => match key.code {
            K::Char(digit @ '1'..='9') if unmodified(key) => {
                Some(A::CountDigit(digit as u8 - b'0'))
            }
            K::Char('0') if unmodified(key) => Some(A::CountDigit(0)),
            K::Char('i') if unmodified(key) => Some(A::EnterInsert),
            K::Char('y') if unmodified(key) => Some(A::Copy),
            K::Char('Y') if unmodified_or_shift(key) => Some(A::CopyVisible),
            K::Char('C') if unmodified_or_shift(key) => Some(A::CopyAll),
            K::Char('c') if unmodified(key) => Some(A::CopyLast),
            K::Enter if unmodified(key) => Some(A::Toggle),
            K::Left | K::Char('h') if unmodified(key) => Some(A::MoveLeft),
            K::Right | K::Char('l') if unmodified(key) => Some(A::MoveRight),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::Char('b') if only_ctrl(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Char(' ') if only_shift(key) => Some(A::PageUp),
            K::Char(' ') if unmodified(key) => Some(A::PageDown),
            K::Char('u') if only_ctrl(key) => Some(A::HalfPageUp),
            K::Char('d') if only_ctrl(key) => Some(A::HalfPageDown),
            K::Home | K::Char('g') if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Char('G') if unmodified_or_shift(key) => Some(A::End),
            _ => None,
        },
        KeyContext::Composer => match key.code {
            K::Esc if unmodified(key) => Some(A::EnterView),
            _ => None,
        },
        KeyContext::ComposerItem => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::BackTab if unmodified_or_shift(key) => Some(A::Previous),
            K::Left | K::Char('h') if unmodified(key) => Some(A::Previous),
            K::Tab | K::Right | K::Char('l') if unmodified(key) => Some(A::Next),
            K::Delete if unmodified(key) => Some(A::Delete),
            K::Enter | K::Char('o') if unmodified(key) => Some(A::Open),
            _ => None,
        },
        KeyContext::PromptHistory => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Char('c') if only_ctrl(key) => Some(A::Close),
            K::Enter if unmodified(key) => Some(A::Accept),
            K::Char('r') if only_ctrl(key) => Some(A::Older),
            K::Up if unmodified(key) => Some(A::Previous),
            K::Down if unmodified(key) => Some(A::Next),
            K::Up if only_alt(key) => Some(A::Older),
            K::Down if only_alt(key) => Some(A::Newer),
            K::Char('s') if only_ctrl(key) => Some(A::NewerKeepOpen),
            _ => None,
        },
        KeyContext::Suggestion => match key.code {
            K::Up if unmodified(key) => Some(A::Previous),
            K::Char('p') if only_ctrl(key) => Some(A::Previous),
            K::Down if unmodified(key) => Some(A::Next),
            K::Char('n') if only_ctrl(key) => Some(A::Next),
            K::Esc if unmodified(key) => Some(A::Close),
            K::Tab if unmodified(key) => Some(A::Fill),
            K::Enter if unmodified(key) => Some(A::Accept),
            _ => None,
        },
        KeyContext::Help => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            _ => None,
        },
        KeyContext::Choice | KeyContext::FileAttach => match key.code {
            K::Enter if unmodified(key) => Some(A::Accept),
            _ => None,
        },
        KeyContext::SessionSearch => match key.code {
            K::Enter if unmodified(key) => Some(A::Open),
            _ => None,
        },
        KeyContext::Picker => match key.code {
            K::Enter if unmodified(key) => Some(A::Accept),
            _ => None,
        },
        KeyContext::SessionModel => match key.code {
            K::Enter if unmodified(key) => Some(A::Accept),
            _ => None,
        },
        KeyContext::Timeline => match key.code {
            K::Enter if unmodified(key) => Some(A::Open),
            _ => None,
        },
        KeyContext::Confirm => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Enter if unmodified(key) => Some(A::Confirm),
            K::Char('y' | 'Y') if unmodified_or_shift(key) => Some(A::Confirm),
            _ => None,
        },
        KeyContext::PermissionPrompt => match key.code {
            K::Esc if unmodified(key) => Some(A::Back),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            K::Enter if unmodified(key) => Some(A::Activate),
            _ => None,
        },
        KeyContext::UserInputQuestion => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Enter if unmodified(key) => Some(A::Accept),
            K::Char('x') if only_ctrl(key) => Some(A::CancelRequest),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            K::Tab if unmodified(key) => Some(A::NextTab),
            K::Char(' ') if unmodified(key) => Some(A::Toggle),
            K::Char('e') if unmodified(key) => Some(A::Edit),
            K::Delete if unmodified(key) => Some(A::Clear),
            _ => None,
        },
        KeyContext::UserInputReview => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Enter if unmodified(key) => Some(A::Accept),
            K::Char('x') if only_ctrl(key) => Some(A::CancelRequest),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Char('e') if unmodified(key) => Some(A::Edit),
            K::Delete if unmodified(key) => Some(A::Clear),
            _ => None,
        },
        _ => None,
    }
}
