use crossterm::event::{KeyCode as K, KeyEvent, KeyModifiers};

use super::{KeyAction as A, KeyContext};

pub(super) fn resolve(context: KeyContext, key: KeyEvent) -> Option<A> {
    let ctrl = key.modifiers.contains(KeyModifiers::CONTROL);
    let alt = key.modifiers.contains(KeyModifiers::ALT);
    let shift = key.modifiers.contains(KeyModifiers::SHIFT);
    match context {
        KeyContext::Global => match key.code {
            K::Char('c') if ctrl => Some(A::Interrupt),
            _ => None,
        },
        KeyContext::Main => match key.code {
            K::Char('/') if !ctrl && !alt => Some(A::SearchForward),
            K::Char('?') if !ctrl && !alt => Some(A::SearchBackward),
            K::Char('N') if !ctrl && !alt => Some(A::SearchPrevious),
            K::Char('n') if !ctrl && !alt => Some(A::SearchNext),
            K::Char('r') if !ctrl && !alt => Some(A::Continue),
            _ => None,
        },
        KeyContext::Sessions => match key.code {
            K::Char('1') => Some(A::ModeAll),
            K::Char('2') => Some(A::ModeRoots),
            K::Char('3') => Some(A::ModeSubtree),
            K::Char('m') => Some(A::ModeCycle),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Enter => Some(A::Open),
            _ => None,
        },
        KeyContext::Transcript => match key.code {
            K::Char(digit @ '1'..='9') if !ctrl && !alt => Some(A::CountDigit(digit as u8 - b'0')),
            K::Char('0') if !ctrl && !alt => Some(A::CountDigit(0)),
            K::Char('i') if !ctrl && !alt => Some(A::EnterInsert),
            K::Char('y') if !ctrl && !alt => Some(A::Copy),
            K::Char('Y') if !ctrl && !alt => Some(A::CopyVisible),
            K::Char('C') if !ctrl && !alt => Some(A::CopyAll),
            K::Char('c') if !ctrl && !alt => Some(A::CopyLast),
            K::Enter => Some(A::Toggle),
            K::Left | K::Char('h') if !ctrl && !alt => Some(A::MoveLeft),
            K::Right | K::Char('l') if !ctrl && !alt => Some(A::MoveRight),
            K::Up | K::Char('k') if !ctrl && !alt => Some(A::MoveUp),
            K::Down | K::Char('j') if !ctrl && !alt => Some(A::MoveDown),
            K::PageUp => Some(A::PageUp),
            K::Char('b') if ctrl => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Char(' ') if shift => Some(A::PageUp),
            K::Char(' ') if !ctrl && !alt => Some(A::PageDown),
            K::Char('u') if ctrl => Some(A::HalfPageUp),
            K::Char('d') if ctrl => Some(A::HalfPageDown),
            K::Home | K::Char('g') if !ctrl && !alt => Some(A::Home),
            K::End | K::Char('G') if !ctrl && !alt => Some(A::End),
            _ => None,
        },
        KeyContext::Composer => match key.code {
            K::Esc if key.modifiers.is_empty() => Some(A::EnterView),
            K::Up if alt || key.modifiers.is_empty() => Some(A::Older),
            _ => None,
        },
        KeyContext::ComposerItem => match key.code {
            K::Esc if key.modifiers.is_empty() => Some(A::Close),
            K::BackTab | K::Left | K::Char('h') => Some(A::Previous),
            K::Tab | K::Right | K::Char('l') => Some(A::Next),
            K::Delete | K::Backspace | K::Char('d') => Some(A::Delete),
            K::Enter | K::Char('o') => Some(A::Open),
            _ => None,
        },
        KeyContext::PromptHistory => match key.code {
            K::Esc if key.modifiers.is_empty() => Some(A::Close),
            K::Char('c') if ctrl => Some(A::Close),
            K::Enter if key.modifiers.is_empty() => Some(A::Accept),
            K::Char('r') if ctrl => Some(A::Older),
            K::Up if key.modifiers.is_empty() || alt => Some(A::Older),
            K::Down if key.modifiers.is_empty() || alt => Some(A::Newer),
            K::Char('s') if ctrl => Some(A::NewerKeepOpen),
            _ => None,
        },
        KeyContext::Suggestion => match key.code {
            K::Up => Some(A::Previous),
            K::Char('p') if ctrl => Some(A::Previous),
            K::Down => Some(A::Next),
            K::Char('n') if ctrl => Some(A::Next),
            K::Esc => Some(A::Close),
            K::Tab => Some(A::Fill),
            K::Enter if key.modifiers.is_empty() => Some(A::Accept),
            _ => None,
        },
        KeyContext::Help => match key.code {
            K::Esc | K::Char('?') | K::Char('q') => Some(A::Close),
            _ => None,
        },
        KeyContext::Choice | KeyContext::FileAttach => match key.code {
            K::Tab => Some(A::Fill),
            K::Enter => Some(A::Accept),
            _ => None,
        },
        KeyContext::SessionSearch => match key.code {
            K::Left | K::Char('h') => Some(A::Previous),
            K::Right | K::Char('l') => Some(A::Next),
            K::Tab => Some(A::Fill),
            K::Enter => Some(A::Open),
            _ => None,
        },
        KeyContext::Picker => match key.code {
            K::Tab => Some(A::Fill),
            K::Char('n') => Some(A::New),
            K::Char('d') => Some(A::Delete),
            K::Enter => Some(A::Accept),
            _ => None,
        },
        KeyContext::SessionModel => match key.code {
            K::Left => Some(A::Previous),
            K::Right => Some(A::Next),
            K::Enter => Some(A::Accept),
            _ => None,
        },
        KeyContext::Timeline => match key.code {
            K::Enter => Some(A::Open),
            K::Char('y') if ctrl => Some(A::CopyEvent),
            _ => None,
        },
        KeyContext::Confirm => match key.code {
            K::Esc => Some(A::Close),
            K::Enter | K::Char('y') | K::Char('Y') => Some(A::Confirm),
            _ => None,
        },
        KeyContext::PermissionPrompt => match key.code {
            K::Char('i') => Some(A::Details),
            K::Esc | K::Left => Some(A::Back),
            K::Up => Some(A::MoveUp),
            K::Down => Some(A::MoveDown),
            K::Enter | K::Right => Some(A::Activate),
            _ => None,
        },
        KeyContext::UserInputQuestion => match key.code {
            K::Esc => Some(A::Close),
            K::Enter => Some(A::Accept),
            K::Char('d') if ctrl => Some(A::CancelRequest),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::PageUp => Some(A::PreviousQuestion),
            K::PageDown => Some(A::NextQuestion),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::BackTab | K::Left | K::Char('h') => Some(A::PreviousTab),
            K::Tab | K::Right | K::Char('l') => Some(A::NextTab),
            K::Char(' ') => Some(A::Toggle),
            K::Char('e') => Some(A::Edit),
            K::Char('c') | K::Delete | K::Backspace => Some(A::Clear),
            _ => None,
        },
        KeyContext::UserInputReview => match key.code {
            K::Esc => Some(A::Close),
            K::Enter => Some(A::Accept),
            K::Char('d') if ctrl => Some(A::CancelRequest),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Char('e') | K::BackTab | K::Left | K::Char('h') => Some(A::Edit),
            K::Char('c') | K::Delete | K::Backspace => Some(A::Clear),
            _ => None,
        },
        _ => None,
    }
}
