use crossterm::event::{KeyCode as K, KeyEvent};

use super::{KeyAction as A, KeyContext, only_ctrl, unmodified, unmodified_or_shift};

pub(super) fn resolve(context: KeyContext, key: KeyEvent) -> Option<A> {
    match context {
        KeyContext::PluginPolicy => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Tab if unmodified(key) => Some(A::Toggle),
            K::BackTab if unmodified_or_shift(key) => Some(A::Toggle),
            K::Enter if unmodified(key) => Some(A::Activate),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Left if unmodified(key) => Some(A::MoveLeft),
            K::Right if unmodified(key) => Some(A::MoveRight),
            K::Delete | K::Backspace if unmodified(key) => Some(A::ClearOverride),
            _ => None,
        },
        KeyContext::PluginList => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Tab if unmodified(key) => Some(A::NextTab),
            K::BackTab if unmodified_or_shift(key) => Some(A::PreviousTab),
            K::Enter if unmodified(key) => Some(A::Open),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if only_ctrl(key) => Some(A::Home),
            K::End if only_ctrl(key) => Some(A::End),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            _ => None,
        },
        KeyContext::PluginDetail => match key.code {
            K::Esc if unmodified(key) => Some(A::Back),
            K::Tab if unmodified(key) => Some(A::NextTab),
            K::BackTab if unmodified_or_shift(key) => Some(A::PreviousTab),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            _ => None,
        },
        KeyContext::PluginConfig => match key.code {
            K::Esc if unmodified(key) => Some(A::Back),
            K::Tab if unmodified(key) => Some(A::NextTab),
            K::BackTab if unmodified_or_shift(key) => Some(A::PreviousTab),
            K::Enter if unmodified(key) => Some(A::Edit),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Left if unmodified(key) => Some(A::MoveLeft),
            K::Right if unmodified(key) => Some(A::MoveRight),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            _ => None,
        },
        KeyContext::PluginConfigActions => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Enter if unmodified(key) => Some(A::Accept),
            _ => None,
        },
        KeyContext::PluginConfigSelection => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Char(' ') if unmodified(key) => Some(A::Toggle),
            K::Enter if unmodified(key) => Some(A::Accept),
            _ => None,
        },
        KeyContext::PluginDrilldown => match key.code {
            K::Esc if unmodified(key) => Some(A::Back),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Left if unmodified(key) => Some(A::MoveLeft),
            K::Right if unmodified(key) => Some(A::MoveRight),
            K::Enter if unmodified(key) => Some(A::Edit),
            _ => None,
        },
        _ => None,
    }
}
