use crossterm::event::{KeyCode as K, KeyEvent, KeyModifiers};

use super::{KeyAction as A, KeyContext};

pub(super) fn resolve(context: KeyContext, key: KeyEvent) -> Option<A> {
    let ctrl = key.modifiers.contains(KeyModifiers::CONTROL);
    match context {
        KeyContext::PluginPolicy => match key.code {
            K::Esc => Some(A::Close),
            K::Tab | K::BackTab => Some(A::Toggle),
            K::Enter => Some(A::Activate),
            K::Char('r') | K::Char('R') => Some(A::Refresh),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Left | K::Char('h') => Some(A::MoveLeft),
            K::Right | K::Char('l') => Some(A::MoveRight),
            K::Delete | K::Backspace => Some(A::ClearOverride),
            K::Char('b') | K::Char('B') => Some(A::Brief),
            K::Char('d') | K::Char('D') => Some(A::Detailed),
            K::Char('s') | K::Char('S') => Some(A::Summary),
            K::Char('x') | K::Char('X') | K::Char('0') => Some(A::ClearOverride),
            _ => None,
        },
        KeyContext::PluginList => match key.code {
            K::Esc => Some(A::Close),
            K::Enter => Some(A::Open),
            K::Char('r') | K::Char('R') => Some(A::Refresh),
            K::Char('t') => Some(A::TransportFilter),
            K::Char('c') => Some(A::ConfigFilter),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            _ => None,
        },
        KeyContext::PluginDetail => match key.code {
            K::Esc => Some(A::Back),
            K::Char('r') | K::Char('R') => Some(A::Refresh),
            K::Tab | K::Down | K::Char('j') => Some(A::NextTab),
            K::BackTab | K::Up | K::Char('k') => Some(A::PreviousTab),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Left | K::Char('h') if ctrl => Some(A::PreviousTab),
            K::Right | K::Char('l') if ctrl => Some(A::NextTab),
            _ => None,
        },
        KeyContext::PluginConfig => match key.code {
            K::Esc => Some(A::Close),
            K::Tab => Some(A::NextTab),
            K::BackTab => Some(A::PreviousTab),
            K::Char('s') | K::Char('S') => Some(A::Save),
            K::Char('v') | K::Char('V') => Some(A::Validate),
            K::Char('i') | K::Char('I') => Some(A::InsertDefaults),
            K::Char('x') | K::Char('X') => Some(A::Actions),
            K::Char('d') if ctrl => Some(A::Delete),
            K::Char('d') => Some(A::CloseDiff),
            K::Char('D') => Some(A::ShowDiff),
            K::Char('r') if ctrl => Some(A::Restart),
            K::Char('r') => Some(A::Reset),
            K::Char('a') | K::Char('A') => Some(A::Add),
            K::Char('t') | K::Char('T') => Some(A::SelectType),
            K::Enter | K::Char('e') => Some(A::Edit),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Left | K::Char('h') => Some(A::MoveLeft),
            K::Right | K::Char('l') => Some(A::MoveRight),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            _ => None,
        },
        KeyContext::PluginConfigActions => match key.code {
            K::Esc => Some(A::Close),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Enter => Some(A::Accept),
            _ => None,
        },
        KeyContext::PluginConfigSelection => match key.code {
            K::Esc => Some(A::Close),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Char(' ') => Some(A::Toggle),
            K::Enter => Some(A::Accept),
            _ => None,
        },
        KeyContext::PluginDrilldown => match key.code {
            K::Esc => Some(A::Back),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Left | K::Char('h') => Some(A::MoveLeft),
            K::Right | K::Char('l') => Some(A::MoveRight),
            K::Char('a') | K::Char('A') => Some(A::Add),
            K::Char('x') | K::Char('X') => Some(A::Actions),
            K::Char('t') | K::Char('T') => Some(A::SelectType),
            K::Char('d') if ctrl => Some(A::Delete),
            K::Enter | K::Char('e') => Some(A::Edit),
            _ => None,
        },
        _ => None,
    }
}
