use crossterm::event::{KeyCode as K, KeyEvent};

use super::{KeyAction as A, KeyContext, only_alt, only_ctrl, unmodified, unmodified_or_shift};

pub(super) fn resolve(context: KeyContext, key: KeyEvent) -> Option<A> {
    match context {
        KeyContext::PluginPolicy => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Tab if unmodified(key) => Some(A::Toggle),
            K::BackTab if unmodified_or_shift(key) => Some(A::Toggle),
            K::Enter if unmodified(key) => Some(A::Activate),
            K::Char('r') | K::Char('R') if unmodified_or_shift(key) => Some(A::Refresh),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Left | K::Char('h') if unmodified(key) => Some(A::MoveLeft),
            K::Right | K::Char('l') if unmodified(key) => Some(A::MoveRight),
            K::Delete | K::Backspace if unmodified(key) => Some(A::ClearOverride),
            K::Char('b') | K::Char('B') if unmodified_or_shift(key) => Some(A::Brief),
            K::Char('d') | K::Char('D') if unmodified_or_shift(key) => Some(A::Detailed),
            K::Char('s') | K::Char('S') if unmodified_or_shift(key) => Some(A::Summary),
            K::Char('x') | K::Char('X') if unmodified_or_shift(key) => Some(A::ClearOverride),
            K::Char('0') if unmodified(key) => Some(A::ClearOverride),
            _ => None,
        },
        KeyContext::PluginList => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Enter if unmodified(key) => Some(A::Open),
            K::Char('r') if only_ctrl(key) => Some(A::Refresh),
            K::Char('t') if only_alt(key) => Some(A::TransportFilter),
            K::Char('c') if only_alt(key) => Some(A::ConfigFilter),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if only_ctrl(key) => Some(A::Home),
            K::End if only_ctrl(key) => Some(A::End),
            K::Up if unmodified(key) => Some(A::MoveUp),
            K::Down if unmodified(key) => Some(A::MoveDown),
            _ => None,
        },
        KeyContext::PluginDetail => match key.code {
            K::Left | K::Char('h') if only_ctrl(key) => Some(A::PreviousTab),
            K::Right | K::Char('l') if only_ctrl(key) => Some(A::NextTab),
            K::Esc if unmodified(key) => Some(A::Back),
            K::Char('r') | K::Char('R') if unmodified_or_shift(key) => Some(A::Refresh),
            K::Tab | K::Down | K::Char('j') if unmodified(key) => Some(A::NextTab),
            K::BackTab if unmodified_or_shift(key) => Some(A::PreviousTab),
            K::Up | K::Char('k') if unmodified(key) => Some(A::PreviousTab),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            _ => None,
        },
        KeyContext::PluginConfig => match key.code {
            K::Left | K::Char('h') if only_ctrl(key) => Some(A::Previous),
            K::Right | K::Char('l') if only_ctrl(key) => Some(A::Next),
            K::Char('d') if only_ctrl(key) => Some(A::Delete),
            K::Char('r') if only_ctrl(key) => Some(A::Restart),
            K::Esc if unmodified(key) => Some(A::Back),
            K::Tab if unmodified(key) => Some(A::NextTab),
            K::BackTab if unmodified_or_shift(key) => Some(A::PreviousTab),
            K::Char('s') | K::Char('S') if unmodified_or_shift(key) => Some(A::Save),
            K::Char('v') | K::Char('V') if unmodified_or_shift(key) => Some(A::Validate),
            K::Char('i') | K::Char('I') if unmodified_or_shift(key) => Some(A::InsertDefaults),
            K::Char('x') | K::Char('X') if unmodified_or_shift(key) => Some(A::Actions),
            K::Char('D') if unmodified_or_shift(key) => Some(A::ShowDiff),
            K::Char('R') if unmodified_or_shift(key) => Some(A::Refresh),
            K::Char('r') if unmodified(key) => Some(A::Reset),
            K::Char('a') | K::Char('A') if unmodified_or_shift(key) => Some(A::Add),
            K::Char('t') | K::Char('T') if unmodified_or_shift(key) => Some(A::SelectType),
            K::Enter | K::Char('e') if unmodified(key) => Some(A::Edit),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Left | K::Char('h') if unmodified(key) => Some(A::MoveLeft),
            K::Right | K::Char('l') if unmodified(key) => Some(A::MoveRight),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            _ => None,
        },
        KeyContext::PluginConfigActions => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Enter if unmodified(key) => Some(A::Accept),
            _ => None,
        },
        KeyContext::PluginConfigSelection => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Char(' ') if unmodified(key) => Some(A::Toggle),
            K::Enter if unmodified(key) => Some(A::Accept),
            _ => None,
        },
        KeyContext::PluginDrilldown => match key.code {
            K::Char('d') if only_ctrl(key) => Some(A::Delete),
            K::Esc if unmodified(key) => Some(A::Back),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Left | K::Char('h') if unmodified(key) => Some(A::MoveLeft),
            K::Right | K::Char('l') if unmodified(key) => Some(A::MoveRight),
            K::Char('a') | K::Char('A') if unmodified_or_shift(key) => Some(A::Add),
            K::Char('x') | K::Char('X') if unmodified_or_shift(key) => Some(A::Actions),
            K::Char('t') | K::Char('T') if unmodified_or_shift(key) => Some(A::SelectType),
            K::Enter | K::Char('e') if unmodified(key) => Some(A::Edit),
            _ => None,
        },
        _ => None,
    }
}
