use crossterm::event::{KeyCode as K, KeyEvent};

use super::{KeyAction as A, KeyContext};

pub(super) fn resolve(context: KeyContext, key: KeyEvent) -> Option<A> {
    match context {
        KeyContext::SettingsStudio => match key.code {
            K::Esc => Some(A::Close),
            K::Char('r') => Some(A::Refresh),
            K::Tab | K::Right | K::Char('l') => Some(A::NextTab),
            K::BackTab | K::Left | K::Char('h') => Some(A::PreviousTab),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::Enter => Some(A::Activate),
            _ => None,
        },
        KeyContext::AgentStudio => match key.code {
            K::Esc => Some(A::Close),
            K::Char('r') => Some(A::Refresh),
            K::Char('o') => Some(A::Open),
            K::Char('p') => Some(A::Details),
            K::Enter => Some(A::Activate),
            _ => None,
        },
        KeyContext::PermissionStudio => match key.code {
            K::Esc => Some(A::Back),
            K::Char('r') => Some(A::Refresh),
            K::Char('a') => Some(A::Add),
            K::Char('e') => Some(A::Edit),
            K::Char('n') => Some(A::Rename),
            K::Char('y') => Some(A::Duplicate),
            K::Char('d') => Some(A::Delete),
            K::Tab | K::Right | K::Char('l') => Some(A::NextTab),
            K::BackTab | K::Left | K::Char('h') => Some(A::PreviousTab),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::Enter => Some(A::Activate),
            _ => None,
        },
        KeyContext::PermissionRuleStudio => match key.code {
            K::Esc => Some(A::Close),
            K::Char('r') => Some(A::Refresh),
            K::Char('b') => Some(A::Browse),
            K::Enter => Some(A::Activate),
            _ => None,
        },
        KeyContext::PathBrowser => match key.code {
            K::Tab => Some(A::Fill),
            K::Char('h') => Some(A::Back),
            K::Char('l') => Some(A::Open),
            K::Enter => Some(A::Accept),
            _ => None,
        },
        KeyContext::ProviderStudio => match key.code {
            K::Esc => Some(A::Close),
            K::Tab => Some(A::NextTab),
            K::BackTab => Some(A::PreviousTab),
            K::Char('n') => Some(A::New),
            K::Char('o') | K::Char('O') => Some(A::AuthStart),
            K::Char('p') | K::Char('P') => Some(A::AuthContinue),
            K::Char('r') => Some(A::LoadModels),
            K::Char('+') => Some(A::Add),
            K::Delete | K::Backspace => Some(A::Delete),
            K::Char('D') => Some(A::DeleteProvider),
            K::Char('s') | K::Char('S') => Some(A::Save),
            K::Char('a') => Some(A::SaveAdapter),
            K::Char('A') => Some(A::SelectAll),
            K::Char('c') | K::Char('C') => Some(A::Clear),
            K::Char('m') | K::Char('M') => Some(A::SaveModel),
            K::Char(' ') => Some(A::Toggle),
            K::PageUp => Some(A::PageUp),
            K::PageDown => Some(A::PageDown),
            K::Home => Some(A::Home),
            K::End => Some(A::End),
            K::Up | K::Char('k') => Some(A::MoveUp),
            K::Down | K::Char('j') => Some(A::MoveDown),
            K::Enter => Some(A::Activate),
            _ => None,
        },
        KeyContext::ProviderDetail => match key.code {
            K::Esc => Some(A::Back),
            K::Char('o') | K::Char('O') => Some(A::AuthStart),
            K::Char('p') | K::Char('P') => Some(A::AuthContinue),
            K::Enter => Some(A::Activate),
            _ => None,
        },
        KeyContext::ProviderModel => match key.code {
            K::Esc => Some(A::Back),
            K::Char('s') | K::Char('S') => Some(A::Save),
            K::Char('d') | K::Delete | K::Backspace => Some(A::Delete),
            K::Enter => Some(A::Activate),
            _ => None,
        },
        KeyContext::ModelCatalog => match key.code {
            K::Esc => Some(A::Close),
            K::Char('/') => Some(A::CatalogSearch),
            K::Char('R') => Some(A::CatalogRefresh),
            K::Left | K::Char('h') => Some(A::Previous),
            K::Right | K::Char('l') => Some(A::Next),
            _ => None,
        },
        _ => None,
    }
}
