use crossterm::event::{KeyCode as K, KeyEvent};

use super::{KeyAction as A, KeyContext, only_alt, unmodified, unmodified_or_shift};

pub(super) fn resolve(context: KeyContext, key: KeyEvent) -> Option<A> {
    match context {
        KeyContext::SettingsStudio => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Char('r') if unmodified(key) => Some(A::Refresh),
            K::Tab | K::Right | K::Char('l') if unmodified(key) => Some(A::NextTab),
            K::BackTab if unmodified_or_shift(key) => Some(A::PreviousTab),
            K::Left | K::Char('h') if unmodified(key) => Some(A::PreviousTab),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            K::Enter if unmodified(key) => Some(A::Activate),
            _ => None,
        },
        KeyContext::AgentStudio => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Char('r') if unmodified(key) => Some(A::Refresh),
            K::Char('o') if unmodified(key) => Some(A::Open),
            K::Char('p') if unmodified(key) => Some(A::Details),
            K::Enter if unmodified(key) => Some(A::Activate),
            _ => None,
        },
        KeyContext::PermissionStudio => match key.code {
            K::Esc if unmodified(key) => Some(A::Back),
            K::Char('r') if unmodified(key) => Some(A::Refresh),
            K::Char('a') if unmodified(key) => Some(A::Add),
            K::Char('e') if unmodified(key) => Some(A::Edit),
            K::Char('n') if unmodified(key) => Some(A::Rename),
            K::Char('y') if unmodified(key) => Some(A::Duplicate),
            K::Char('d') if unmodified(key) => Some(A::Delete),
            K::Tab | K::Right | K::Char('l') if unmodified(key) => Some(A::NextTab),
            K::BackTab if unmodified_or_shift(key) => Some(A::PreviousTab),
            K::Left | K::Char('h') if unmodified(key) => Some(A::PreviousTab),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            K::Enter if unmodified(key) => Some(A::Activate),
            _ => None,
        },
        KeyContext::PermissionRuleStudio => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Char('r') if unmodified(key) => Some(A::Refresh),
            K::Char('b') if unmodified(key) => Some(A::Browse),
            K::Enter if unmodified(key) => Some(A::Activate),
            _ => None,
        },
        KeyContext::PathBrowser => match key.code {
            K::Tab if unmodified(key) => Some(A::Fill),
            K::Up if only_alt(key) => Some(A::Back),
            K::Down if only_alt(key) => Some(A::Open),
            K::Enter if unmodified(key) => Some(A::Accept),
            _ => None,
        },
        KeyContext::ProviderStudio => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Tab if unmodified(key) => Some(A::NextTab),
            K::BackTab if unmodified_or_shift(key) => Some(A::PreviousTab),
            K::Char('n') if unmodified(key) => Some(A::New),
            K::Char('o') | K::Char('O') if unmodified_or_shift(key) => Some(A::AuthStart),
            K::Char('p') | K::Char('P') if unmodified_or_shift(key) => Some(A::AuthContinue),
            K::Char('r') if unmodified(key) => Some(A::LoadModels),
            K::Char('+') if unmodified_or_shift(key) => Some(A::Add),
            K::Delete | K::Backspace if unmodified(key) => Some(A::Delete),
            K::Char('D') if unmodified_or_shift(key) => Some(A::DeleteProvider),
            K::Char('s') | K::Char('S') if unmodified_or_shift(key) => Some(A::Save),
            K::Char('a') if unmodified(key) => Some(A::SaveAdapter),
            K::Char('A') if unmodified_or_shift(key) => Some(A::SelectAll),
            K::Char('c') | K::Char('C') if unmodified_or_shift(key) => Some(A::Clear),
            K::Char('m') | K::Char('M') if unmodified_or_shift(key) => Some(A::SaveModel),
            K::Char(' ') if unmodified(key) => Some(A::Toggle),
            K::PageUp if unmodified(key) => Some(A::PageUp),
            K::PageDown if unmodified(key) => Some(A::PageDown),
            K::Home if unmodified(key) => Some(A::Home),
            K::End if unmodified(key) => Some(A::End),
            K::Up | K::Char('k') if unmodified(key) => Some(A::MoveUp),
            K::Down | K::Char('j') if unmodified(key) => Some(A::MoveDown),
            K::Enter if unmodified(key) => Some(A::Activate),
            _ => None,
        },
        KeyContext::ProviderDetail => match key.code {
            K::Esc if unmodified(key) => Some(A::Back),
            K::Char('o') | K::Char('O') if unmodified_or_shift(key) => Some(A::AuthStart),
            K::Char('p') | K::Char('P') if unmodified_or_shift(key) => Some(A::AuthContinue),
            K::Enter if unmodified(key) => Some(A::Activate),
            _ => None,
        },
        KeyContext::ProviderModel => match key.code {
            K::Esc if unmodified(key) => Some(A::Back),
            K::Char('s') | K::Char('S') if unmodified_or_shift(key) => Some(A::Save),
            K::Char('d') | K::Delete | K::Backspace if unmodified(key) => Some(A::Delete),
            K::Enter if unmodified(key) => Some(A::Activate),
            _ => None,
        },
        KeyContext::ModelCatalog => match key.code {
            K::Esc if unmodified(key) => Some(A::Close),
            K::Char('/') if unmodified(key) => Some(A::CatalogSearch),
            K::Char('R') if unmodified_or_shift(key) => Some(A::CatalogRefresh),
            K::Left | K::Char('h') if unmodified(key) => Some(A::Previous),
            K::Right | K::Char('l') if unmodified(key) => Some(A::Next),
            _ => None,
        },
        _ => None,
    }
}
