[package]
name = "agena-mcp-client"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
arc-swap = "1.7.1"
async-trait = { workspace = true }
dashmap = "6.1.0"
eventsource-stream = "0.2.3"
futures-util = "0.3.31"
reqwest = { workspace = true, features = ["rustls", "stream", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "process", "io-util", "sync", "time"] }
tracing = { workspace = true }
url = "2.5.4"

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }

[lints]
workspace = true
