use sea_orm::sea_query::{
    Condition, ConditionalStatement, Expr, Index, IndexCreateStatement, TableCreateStatement,
};
use sea_orm::{ConnectionTrait, DatabaseConnection, DbErr, Schema, TransactionTrait};

use crate::db::{entities, event_entity};

/// Bootstraps the current database schema directly.
///
/// Agena creates the current schema from scratch.
pub async fn up(db: &DatabaseConnection) -> Result<(), DbErr> {
    let backend = db.get_database_backend();
    let schema = Schema::new(backend);
    let txn = db.begin().await?;

    for create in table_definitions(&schema) {
        txn.execute(backend.build(&create)).await?;
    }
    for index in index_definitions() {
        txn.execute(backend.build(&index)).await?;
    }

    txn.commit().await
}

fn table_definitions(schema: &Schema) -> Vec<TableCreateStatement> {
    vec![
        schema
            .create_table_from_entity(entities::workspace::Entity)
            .if_not_exists()
            .to_owned(),
        schema
            .create_table_from_entity(entities::session::Entity)
            .if_not_exists()
            .to_owned(),
        schema
            .create_table_from_entity(entities::permission_rule::Entity)
            .if_not_exists()
            .to_owned(),
        schema
            .create_table_from_entity(event_entity::Entity)
            .if_not_exists()
            .to_owned(),
        schema
            .create_table_from_entity(entities::activity_message::Entity)
            .if_not_exists()
            .to_owned(),
        schema
            .create_table_from_entity(entities::activity_part::Entity)
            .if_not_exists()
            .to_owned(),
        schema
            .create_table_from_entity(entities::activity_projection_state::Entity)
            .if_not_exists()
            .to_owned(),
        schema
            .create_table_from_entity(entities::model_catalog_entry::Entity)
            .if_not_exists()
            .to_owned(),
        schema
            .create_table_from_entity(entities::model_catalog_state::Entity)
            .if_not_exists()
            .to_owned(),
    ]
}

fn index_definitions() -> Vec<IndexCreateStatement> {
    vec![
        Index::create()
            .name("uq_agena_workspace_path")
            .table(entities::workspace::Entity)
            .col(entities::workspace::Column::Path)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_session_parent_id")
            .table(entities::session::Entity)
            .col(entities::session::Column::ParentId)
            .col(entities::session::Column::Id)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_session_root_id")
            .table(entities::session::Entity)
            .col(entities::session::Column::RootId)
            .col(entities::session::Column::Depth)
            .col(entities::session::Column::Id)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_agena_session_parent_task_id")
            .table(entities::session::Entity)
            .col(entities::session::Column::ParentId)
            .col(entities::session::Column::TaskId)
            .unique()
            .cond_where(
                Condition::all()
                    .add(Expr::col(entities::session::Column::ParentId).is_not_null())
                    .add(Expr::col(entities::session::Column::TaskId).is_not_null()),
            )
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_session_workspace_id_updated")
            .table(entities::session::Entity)
            .col(entities::session::Column::WorkspaceId)
            .col(entities::session::Column::UpdatedAtMs)
            .col(entities::session::Column::Id)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_agena_permission_rule_global_subject")
            .table(entities::permission_rule::Entity)
            .col(entities::permission_rule::Column::ActionKey)
            .col(entities::permission_rule::Column::Scope)
            .unique()
            .cond_where(
                Condition::all()
                    .add(Expr::col(entities::permission_rule::Column::SessionId).is_null())
                    .add(Expr::col(entities::permission_rule::Column::WorkspaceId).is_null()),
            )
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_agena_permission_rule_workspace_subject")
            .table(entities::permission_rule::Entity)
            .col(entities::permission_rule::Column::ActionKey)
            .col(entities::permission_rule::Column::Scope)
            .col(entities::permission_rule::Column::WorkspaceId)
            .unique()
            .cond_where(
                Condition::all()
                    .add(Expr::col(entities::permission_rule::Column::SessionId).is_null())
                    .add(Expr::col(entities::permission_rule::Column::WorkspaceId).is_not_null()),
            )
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_agena_permission_rule_session_subject")
            .table(entities::permission_rule::Entity)
            .col(entities::permission_rule::Column::ActionKey)
            .col(entities::permission_rule::Column::Scope)
            .col(entities::permission_rule::Column::SessionId)
            .unique()
            .cond_where(
                Condition::all()
                    .add(Expr::col(entities::permission_rule::Column::SessionId).is_not_null())
                    .add(Expr::col(entities::permission_rule::Column::WorkspaceId).is_null()),
            )
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_permission_rule_active_updated")
            .table(entities::permission_rule::Entity)
            .col(entities::permission_rule::Column::RevokedAtMs)
            .col(entities::permission_rule::Column::UpdatedAtMs)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_events_seq_global")
            .table(event_entity::Entity)
            .col(event_entity::Column::SeqGlobal)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_agena_events_session_seq")
            .table(event_entity::Entity)
            .col(event_entity::Column::SessionId)
            .col(event_entity::Column::SeqSession)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_events_workspace_seq")
            .table(event_entity::Entity)
            .col(event_entity::Column::WorkspaceId)
            .col(event_entity::Column::SeqGlobal)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_events_kind_seq")
            .table(event_entity::Entity)
            .col(event_entity::Column::KindTag)
            .col(event_entity::Column::SeqGlobal)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_activity_messages_session_created")
            .table(entities::activity_message::Entity)
            .col(entities::activity_message::Column::SessionId)
            .col(entities::activity_message::Column::CreatedAtMs)
            .col(entities::activity_message::Column::MessageId)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_activity_messages_session_hidden")
            .table(entities::activity_message::Entity)
            .col(entities::activity_message::Column::SessionId)
            .col(entities::activity_message::Column::IsHidden)
            .col(entities::activity_message::Column::CreatedAtMs)
            .col(entities::activity_message::Column::MessageId)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_activity_parts_message_index")
            .table(entities::activity_part::Entity)
            .col(entities::activity_part::Column::MessageId)
            .col(entities::activity_part::Column::PartIndex)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_activity_parts_session_message")
            .table(entities::activity_part::Entity)
            .col(entities::activity_part::Column::SessionId)
            .col(entities::activity_part::Column::MessageId)
            .col(entities::activity_part::Column::PartId)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("uq_agena_model_catalog_kind_model")
            .table(entities::model_catalog_entry::Entity)
            .col(entities::model_catalog_entry::Column::Kind)
            .col(entities::model_catalog_entry::Column::ModelId)
            .unique()
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_model_catalog_model_id")
            .table(entities::model_catalog_entry::Entity)
            .col(entities::model_catalog_entry::Column::ModelId)
            .if_not_exists()
            .to_owned(),
        Index::create()
            .name("idx_agena_model_catalog_kind")
            .table(entities::model_catalog_entry::Entity)
            .col(entities::model_catalog_entry::Column::Kind)
            .if_not_exists()
            .to_owned(),
    ]
}
