[package]
name = "agena-otel"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
opentelemetry = "0.31.0"
opentelemetry-otlp = { version = "0.31.1", default-features = false, features = ["http-proto", "reqwest-blocking-client", "trace"] }
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = "0.32.1"
tracing-subscriber = { workspace = true }

[lints]
workspace = true
