//! Wire contract for the v2 live-update surface.
//!
//! Persisted session history is an ordered list of parts. Live delivery is a
//! best-effort stream of part patches plus ephemeral runtime signals; neither
//! value is persisted or replayed.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// A separately loadable section of a tool-call detail view.
///
/// Transcript list responses load only `presentation` by default. The other
/// sections are fetched from the tool-section endpoint when the user opens
/// them, so large inputs and raw outputs do not cross the transport boundary
/// merely because their disclosure row is collapsed.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[serde(rename_all = "snake_case")]
pub enum ToolDetailSection {
    Metadata,
    Input,
    Output,
    OutputMetadata,
    Presentation,
}

impl ToolDetailSection {
    pub const ALL: [Self; 5] = [
        Self::Metadata,
        Self::Input,
        Self::Output,
        Self::OutputMetadata,
        Self::Presentation,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Metadata => "metadata",
            Self::Input => "input",
            Self::Output => "output",
            Self::OutputMetadata => "output_metadata",
            Self::Presentation => "presentation",
        }
    }
}

impl std::str::FromStr for ToolDetailSection {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value.trim() {
            "metadata" => Ok(Self::Metadata),
            "input" => Ok(Self::Input),
            "output" => Ok(Self::Output),
            "output_metadata" => Ok(Self::OutputMetadata),
            "presentation" => Ok(Self::Presentation),
            other => Err(format!("unknown tool detail section: {other}")),
        }
    }
}

/// The result of fetching one tool-call section.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolDetailResource {
    pub part_id: i64,
    pub section: ToolDetailSection,
    pub value: Value,
}

/// Human-only, read-time projection of a tool call. The durable part contains
/// only the invocation and `RawOutput`; this value exists only on API/live
/// responses and is regenerated by the owning plugin/tool for every read.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ToolHumanPresentationResource {
    pub title: String,
    pub summary: String,
    pub blocks: Vec<agena_domain::ViewBlock>,
}

/// One persisted part as exposed by the public API.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PartResource {
    pub part_id: i64,
    pub kind: String,
    pub role: String,
    pub state: String,
    pub content: Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub presentation: Option<ToolHumanPresentationResource>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    pub visibility: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_part_id: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub run_id: Option<i64>,
    pub origin_session_id: i64,
    pub revision: i64,
    pub started_at_ms: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub finished_at_ms: Option<i64>,
    pub created_at_ms: i64,
    pub updated_at_ms: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_state: Option<Value>,
}

/// Return the canonical tool-call content with only the requested detail
/// sections populated. Identity, lifecycle, error, authorization, and user
/// interaction records remain available because they drive transcript state
/// and actions; potentially large tool sections are omitted until explicitly
/// requested.
pub fn project_tool_call_content(content: &Value, sections: &[ToolDetailSection]) -> Value {
    let Some(object) = content.as_object() else {
        return content.clone();
    };

    let has = |section| sections.contains(&section);
    let mut projected = object.clone();

    if has(ToolDetailSection::Input) {
        if let Some(input) = object.get("input") {
            projected.insert("input".to_owned(), input.clone());
        }
    } else {
        projected.remove("input");
    }

    if has(ToolDetailSection::Metadata) {
        if let Some(metadata) = object.get("metadata") {
            projected.insert("metadata".to_owned(), metadata.clone());
        }
    } else {
        projected.remove("metadata");
    }

    let projected_output =
        if has(ToolDetailSection::Output) || has(ToolDetailSection::OutputMetadata) {
            object.get("output").map(|value| match value {
                Value::Object(output) => {
                    let mut value = output.clone();
                    if !has(ToolDetailSection::OutputMetadata) {
                        value.remove("metadata");
                    }
                    if !has(ToolDetailSection::Output) {
                        value.retain(|key, _| key == "metadata");
                    }
                    Value::Object(value)
                }
                other => other.clone(),
            })
        } else {
            None
        };
    if let Some(output) = projected_output {
        projected.insert("output".to_owned(), output);
    } else {
        projected.remove("output");
    }

    projected.into()
}

/// Presentation metadata for a folded assistant activity prefix. The prefix
/// is intentionally absent from `SessionPartsResource.parts`; clients use the
/// opaque cursor to request the next expansion chunk for the adjacent logical
/// assistant reply.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SessionTranscriptFoldResource {
    pub run_id: i64,
    /// All adjacent assistant runs that make up the folded logical reply.
    /// `run_id` remains the run containing the first visible anchor for
    /// compact clients; expansion uses this complete set.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub run_ids: Vec<i64>,
    /// The first activity part currently present in `parts` for this fold.
    pub anchor_part_id: i64,
    pub hidden_count: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

/// Current ordered part snapshot used for initial load and reconnect catch-up.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SessionPartsResource {
    pub session_id: i64,
    /// Monotonic `sessions.version` high-water mark.
    pub version: i64,
    pub parts: Vec<PartResource>,
    /// Fold metadata is populated only by the presentation-oriented
    /// transcript endpoint. Raw `/parts` pages leave this empty.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub folds: Vec<SessionTranscriptFoldResource>,
    /// Exact count of user-send messages in the session. Raw part snapshots
    /// may omit it; transcript pages populate it so clients can display the
    /// full history size without loading every page first.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_message_count: Option<u64>,
    /// Cursor metadata for newest-first keyset pagination. `parts` itself is
    /// returned chronologically so renderers can append it directly.
    pub page: crate::pagination::PageInfo,
}

#[cfg(test)]
mod tests {
    use super::{
        PartResource, ToolDetailSection, ToolHumanPresentationResource, project_tool_call_content,
    };

    #[test]
    fn tool_presentation_serializes_beside_unchanged_raw_content() {
        let raw_content = serde_json::json!({
            "name": "fs.read",
            "input": {"file_path": "README.md"},
            "state": "completed",
            "output": {"text": "durable raw result"}
        });
        let resource = PartResource {
            part_id: 1,
            kind: "tool_call".to_owned(),
            role: "assistant".to_owned(),
            state: "completed".to_owned(),
            content: raw_content.clone(),
            presentation: Some(ToolHumanPresentationResource {
                title: "Plugin title".to_owned(),
                summary: "Plugin summary".to_owned(),
                blocks: vec![agena_domain::ViewBlock::Markdown {
                    id: None,
                    text: "plugin human projection".to_owned(),
                }],
            }),
            summary: None,
            visibility: "both".to_owned(),
            parent_part_id: None,
            run_id: Some(1),
            origin_session_id: 1,
            revision: 0,
            started_at_ms: 1,
            finished_at_ms: Some(2),
            created_at_ms: 1,
            updated_at_ms: 2,
            provider_state: None,
        };

        let encoded = serde_json::to_value(resource).expect("serialize response projection");

        assert_eq!(encoded["content"], raw_content);
        assert_eq!(encoded["presentation"]["title"], "Plugin title");
        assert_eq!(
            encoded["presentation"]["blocks"][0]["text"],
            "plugin human projection"
        );
        assert!(encoded["content"].get("presentation").is_none());
        assert!(encoded["content"].get("title").is_none());
        assert!(encoded["content"].get("summary").is_none());
        assert!(encoded["content"].get("blocks").is_none());
    }

    #[test]
    fn default_tool_projection_keeps_only_presentation_safe_facts() {
        let content = serde_json::json!({
            "name": "fs.read",
            "input": {"file_path": "README.md"},
            "metadata": {"cache": true},
            "state": "completed",
            "output": {
                "text": "durable raw result",
                "metadata": {"exit_code": 0},
                "payload": {"large": [1, 2, 3]}
            },
            "user_input": {"requests": []}
        });
        let projected = project_tool_call_content(&content, &[ToolDetailSection::Presentation]);

        assert!(projected.get("input").is_none());
        assert!(projected.get("metadata").is_none());
        assert!(projected.get("output").is_none());
        assert_eq!(projected["name"], "fs.read");
        assert_eq!(projected["state"], "completed");
    }

    #[test]
    fn tool_projection_can_load_output_and_output_metadata_independently() {
        let content = serde_json::json!({
            "name": "fs.read",
            "input": {"file_path": "README.md"},
            "metadata": {"cache": true},
            "state": "completed",
            "output": {
                "text": "durable raw result",
                "metadata": {"exit_code": 0},
                "payload": {"large": [1, 2, 3]}
            }
        });
        let output = project_tool_call_content(&content, &[ToolDetailSection::Output]);
        assert_eq!(output["output"]["text"], "durable raw result");
        assert!(output["output"].get("metadata").is_none());
        assert!(output.get("input").is_none());

        let metadata = project_tool_call_content(&content, &[ToolDetailSection::OutputMetadata]);
        assert_eq!(
            metadata["output"],
            serde_json::json!({"metadata": {"exit_code": 0}})
        );
        assert!(metadata.get("input").is_none());
    }
}

/// A committed session mutation. This is observer notification only: it is
/// never persisted, replayed, or assigned a global sequence.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum SessionChangeResource {
    PartAdded {
        session_id: i64,
        part: Box<PartResource>,
    },
    PartUpdated {
        session_id: i64,
        part: Box<PartResource>,
    },
    PartRemoved {
        session_id: i64,
        part_id: i64,
    },
    SessionMetaUpdated {
        session_id: i64,
        version: i64,
        title: String,
        favorite: bool,
        pinned: bool,
        updated_at_ms: i64,
    },
}

impl SessionChangeResource {
    pub fn session_id(&self) -> i64 {
        match self {
            Self::PartAdded { session_id, .. }
            | Self::PartUpdated { session_id, .. }
            | Self::PartRemoved { session_id, .. }
            | Self::SessionMetaUpdated { session_id, .. } => *session_id,
        }
    }
}

/// Ephemeral, non-session runtime signal. `kind` is open-ended; `payload`
/// contains the signal-specific current value.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RuntimeSignalResource {
    pub kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<i64>,
    pub payload: Value,
}
