pub const OPENCODE_PROVIDER_IDS: &[&str] = &[
    "302ai",
    "abacus",
    "aihubmix",
    "alibaba",
    "alibaba-cn",
    "alibaba-coding-plan",
    "alibaba-coding-plan-cn",
    "amazon-bedrock",
    "azure",
    "azure-cognitive-services",
    "bailing",
    "baseten",
    "berget",
    "cerebras",
    "chutes",
    "clarifai",
    "cloudferro-sherlock",
    "cloudflare-ai-gateway",
    "cloudflare-workers-ai",
    "cohere",
    "cortecs",
    "deepinfra",
    "deepseek",
    "dinference",
    "drun",
    "evroc",
    "fastrouter",
    "fireworks-ai",
    "firmware",
    "friendli",
    "github-models",
    "gitlab",
    "google",
    "google-vertex",
    "google-vertex-anthropic",
    "groq",
    "helicone",
    "huggingface",
    "iflowcn",
    "inception",
    "inference",
    "io-net",
    "jiekou",
    "kilo",
    "kimi-for-coding",
    "kuae-cloud-coding-plan",
    "llama",
    "lmstudio",
    "lucidquery",
    "meganova",
    "minimax",
    "minimax-cn",
    "minimax-cn-coding-plan",
    "minimax-coding-plan",
    "mistral",
    "moark",
    "modelscope",
    "moonshotai",
    "moonshotai-cn",
    "morph",
    "nano-gpt",
    "nebius",
    "nova",
    "novita-ai",
    "nvidia",
    "ollama-cloud",
    "openrouter",
    "opencode",
    "opencode-go",
    "ovhcloud",
    "perplexity",
    "perplexity-agent",
    "poe",
    "privatemode-ai",
    "qihang-ai",
    "qiniu-ai",
    "requesty",
    "sap-ai-core",
    "scaleway",
    "siliconflow",
    "siliconflow-cn",
    "stackit",
    "stepfun",
    "submodel",
    "synthetic",
    "tencent-coding-plan",
    "togetherai",
    "upstage",
    "v0",
    "venice",
    "vercel",
    "vivgrid",
    "vultr",
    "wandb",
    "xai",
    "xiaomi",
    "zai",
    "zai-coding-plan",
    "zenmux",
    "zhipuai",
    "zhipuai-coding-plan",
];

pub fn default_base_url(provider_id: &str) -> Option<&'static str> {
    match provider_id {
        "deepseek" => Some("https://api.deepseek.com/v1"),
        "fireworks-ai" => Some("https://api.fireworks.ai/inference/v1"),
        "groq" => Some("https://api.groq.com/openai/v1"),
        "moonshotai" | "kimi-for-coding" => Some("https://api.moonshot.ai/v1"),
        "mistral" => Some("https://api.mistral.ai/v1"),
        "openrouter" => Some("https://openrouter.ai/api/v1"),
        "perplexity" | "perplexity-agent" => Some("https://api.perplexity.ai"),
        "siliconflow" | "siliconflow-cn" => Some("https://api.siliconflow.cn/v1"),
        "togetherai" => Some("https://api.together.xyz/v1"),
        "xai" => Some("https://api.x.ai/v1"),
        "zhipuai" | "zhipuai-coding-plan" => Some("https://open.bigmodel.cn/api/paas/v4"),
        _ => None,
    }
}
