[package]
name = "agena-marketplace-server"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = []
server = ["dep:axum", "dep:tokio", "dep:serde_json"]

[dependencies]
axum = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, features = ["net"], optional = true }

[lints]
workspace = true
